### ISSUE TITLE
Add support for breakpoint debugging

### ISSUE THREAD

**Issue by marek1840** [scalameta/metals#1010]
Adding supporting for breakpoints consists of two parts:
1. Adapting the `setBreakpoints` request sent to the server
2. Resolving the source path for `stackTrace` responses received from the server

### Adapting `setBreakpoints` request
Bloop [cannot resolve FQCN for third-party sources](https://github.com/scalacenter/bloop/issues/1057), so metals needs to map the breakpoints for a given file `/foo/bar/Baz.scala` to the fully qualified name of the class they are specified in (e.g. `foo.bar.Baz$` for objects). These new paths must then be sent to Bloop.
One caveat here is that a single file can contain multiple classes, so we must partition the client request into possibly multiple synthetic requests and then gather the responses into one before sending them to the client.

The source URI for the requests [expected by bloop](https://github.com/scalacenter/bloop/pull/1087) is `dap-fqcn:$FULLY_QUALIFIED_CLASS_NAME`

### Adapting `stackTrace` response
The stack frames returned from bloop are of the form: 
` { name: $SOURCE_FILE_NAME, path: $PACKAGE_PREFIXED_SOURCE_FILE_NAME }`
This does not match the real source paths expected by the client, so we need to adapt those.

To resolve the real source path we must either: 
1. Find the symbol, using the package-prefixed source file name. Since we know the packages, we can derive a symbols possibly matching the expected type. Note, that this will fail for types not matching the source file name.
2. Find the source file for the given `buildTarget` using the source file name. 

The second approach should be used as a complement to the first one to recover from types not matching their source file name.

**Comment by jvican** [comment]
Excellent ticket description, I had missed the fact that `SetBreakpointsRequest` holds a sequence of breakpoints in my discussion at https://github.com/scalacenter/bloop/issues/1057. The proposed implementation looks good to me :+1:

**Comment by jvican** [comment]
An important consideration when implementing this is that clients only send one unique `setBreakpointRequests` per URI. This is really important because if there is more than one the semantics of DAP establish that only the last processed `setBreakpointRequests` takes effect, e.g. the previous ones will be ignored.
  
I recommend to pass to Bloop only those fully qualified class names belonging to third-party sources and not passing them for user-defined Scala sources, which Bloop supports out-of-the-box via a reliable implementation.

**Comment by tgodzik** [comment]
This is already done by @marek1840
