### ISSUE TITLE
Automatically re-connect to the build server

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1191]
Currently, users need to manually trigger the "Connect to build server" command when the build server connection is lost, which happens for example when the computer goes to sleep. It's not obvious at all for users that this command exists or that it fixes the symptoms of a lost build server connection (file save does not trigger compile).

It would be great if Metals automatically detected when the build server connection gets lost and triggered "Connect to build server" behind the scenes.

**Comment by jvican** [comment]
Thanks for opening this ticket! It's true we were missing a ticket for this issue.

Automatically re-connecting to the build server makes sense, this is a workaround for the fact that the socket connection (especially Unix domain sockets) breaks after the laptop goes to sleep. I think it's important we keep in mind this is still a workaround so that we eventually find a fix for the underlying issue and improve our Unix sockets implementation on both Bloop and Metals.
  
I suspect that implementing this work around on the Metals side should be easy enough because the connection should throw `SocketClosedException` or `isClosed` should b etrue. (If this is not the case, we might be in trouble and need to add some heartbreaking capability to either BSP or Bloop, but let's assume this won't be required for now.)
  
If we implement this automatic reconnection, Metals will re-connect to the bloop server every time the user runs `bloop exit`. This can be problematic because Metals might start a version of Bloop that the user doesn't want and the user will need to close Metals to avoid Metals restarting the bloop server immediately after the server is shut down manually. How do we deal with this side-effect?

I propose we don't reconnect manually and instead display users a message notifying them that the connection was lost with some actionable buttons for "Reconnect to build server" | "Not now"

**Comment by olafurpg** [comment]
> If we implement this automatic reconnection, Metals will re-connect to the bloop server every time the user runs bloop exit. This can be problematic because Metals might start a version of Bloop that the user doesn't want and the user will need to close Metals to avoid Metals restarting the bloop server immediately after the server is shut down manually. How do we deal with this side-effect?

That's a good point! Didn't think of it, would be annoying when trying to customize the Bloop version.

> I propose we don't reconnect manually and instead display users a message notifying them that the connection was lost with some actionable buttons for "Reconnect to build server" | "Not now"

I like this :+1:

**Comment by psilospore** [comment]
Hey! I'm interested in doing this. I have a WIP here: https://github.com/scalameta/metals/compare/master...psilospore:master

**Comment by tgodzik** [comment]
@psilospore Hi, that's cool! You might need to look at `BloopServers.scala` and `connectToNewBuildServer` method in `MetalsLanguageServer.scala` to see how a new server is setup and saved. Let us know if you need any help - you can always create a draft PR, so we can take a look.

**Comment by tgodzik** [comment]
@psilospore are you still interested in doing this issue? If you don't have time currently, I might need to work on the fix now, since it will be useful for the upcoming release.

**Comment by psilospore** [comment]
Hey @tgodzik feel free to take it up I don't want to hold it up. I did get a bit busy recently so otherwise I might not get to it for a while.
