### ISSUE TITLE
Diagnostics have a confusing "code"

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#1220]
**Describe the bug**

Compile errors are displayed in a confusing way

<img width="822" alt="Screenshot 2019-12-23 at 21 33 17" src="https://user-images.githubusercontent.com/1408093/71379922-8f3ec380-25cd-11ea-969d-07271fceef7a.png">

Notice the "bloop(val map: Map(..." part. I expected that to be only "bloop"

The culprit seems to be the "code" field for diagnostic

```json
[Trace - 09:32:17 PM] Sending notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///Users/lgeirsson/dev/geirsson.com/mark/src/main/scala/blog/Post.scala",
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 5,
          "character": 30
        },
        "end": {
          "line": 5,
          "character": 40
        }
      },
      "severity": 1,
      "code": "  val map: Map[Int, String] \u003d expression",
      "source": "bloop",
      "message": "type mismatch;\n found   : scala.collection.immutable.Map[Int,Boolean]\n required: Map[Int,String]"
    }
  ]
}
```
I think the "code" field is only supposed to contain information like "E20" for the category of the error

**Comment by gabro** [comment]
We use the `code` sent by via BSP, so I think Bloop is at fault here.

Here's the relevant code in Bloop where `code` is set to the diagnostic's line content.

https://github.com/scalacenter/bloop/blob/5aa55334a2c154fbe05a75a397c0ba6a077a8577/frontend/src/main/scala/bloop/logging/BspServerLogger.scala#L115-L116

Since `Diagnostic` in BSP is defined as in LSP I think this is just a minor misinterpretation of the `code` property which should be fixed in Bloop.

@jvican what do you think? I can contribute the (very simple) fix if you agree

**Comment by gabro** [comment]
I've opened an issue (with respective PR) on bloop. We can close this once this is fixed on Bloop's side and we upgrade to the latest release.
