### ISSUE TITLE
Presentation compiler and semanticDB indexing should wait until first compilation is finished

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1259]
**Describe the bug**

Reported by @jvican - I will most likely pick it up this month.

"Metals is incorrectly assuming that compile products (both semanticdb files and class files) are available in the project classes directories as soon as Metals connects to Bloop. This is not the case.
As a result, Metals often doesn't fully index semanticdb files (which means go to definition often doesn't work) and the presentation compiler produces wrong results (many `Any`s, for example, and generally doesn't work)
To fix this issue, we should change Metals to not assume the compile products are available and trigger a cascade compile in the whole workspace and wait for its result. Only then Metals can assume there will be some semanticdb and class files in the project dirs."

**To Reproduce**
1. Any first compilation.

**Search terms**
compilation indexing semanticdb

**Comment by olafurpg** [comment]
I agree Metals should trigger compiles before doing some parts of its indexing pipeline.

I think we also need to change Bloop to copy classfiles to a new `classDirectory` even when the project has compile errors. I have seen case where completions/hover/... stop working when you run "connect to build server" or reload VS Code. The reason seems to be that every BSP session starts with empty `classDirectory` and the classfiles get copied over on the first successful compilation. 

To confirm this is the case, I just introduced a compile error in my project, ran "connect to build server", looked at "classDirectory" from the BSP trace and the directory is empty
```
❯ tree /Users/lgeirsson/dev/metals/.bloop/metals/bloop-bsp-clients-classes/classes-Metals-Nv2oElmeTueKCy9gRgrfUA==/
/Users/lgeirsson/dev/metals/.bloop/metals/bloop-bsp-clients-classes/classes-Metals-Nv2oElmeTueKCy9gRgrfUA==
└── META-INF
   └── semanticdb
```

**Comment by m4dc4p** [comment]
@olafurpg This is fantastic info. I think metals (vs code) does this to me frequently. So far, my solution has been to delete `.metals` and `.bloop` and re-import.

**Comment by tgodzik** [comment]
@m4dc4p  That shouldn't be needed, `.bloop` contain mostly config files (aside from artifact directories) needed for Bloop to compile and reimporting will create the exact same files. Removing the directories inside `.bloop` might only be needed in case of corrupted class files. `.metals` doesn't really contain anything that could cause any issues.

Running `Developer: Reload window` is entirely enough to deal with the issues.

**Comment by tgodzik** [comment]
This also causes parsing errors to come up for Scala 3 codebases - rambo presentation compiler is used before connecting to Bloop.
