### ISSUE TITLE
Navigation errors on a project with symlinks

### ISSUE THREAD

**Issue by aldtid** [scalameta/metals#1370]
**Question**

While working with Metals on VSCode in an SBT project with symlinks, some strange navigation error logs appear if a navigation is performed from a file that is in a directory pointed by a symlink:

https://github.com/aldtid/sbt-project-with-symlinks/blob/be6e1f067fce1783c1706acbe2a03bcc378cff16/metals.log#L100

However, navigation can still be made. As this is my first time trying Metals, I cannot say if these errors prevent a normal extension behavior or everything is working as expected. Are these logs relevant?

Thanks in advance.

**Installation:**

- **Operating system**: Linux (NixOS 19.09)
- **Editor**: Visual Studio Code
- **Metals version**: v0.8.0

**Additional context**

I have uploaded an example project with symlinks to easily reproduce this issue: https://github.com/aldtid/sbt-project-with-symlinks

**Search terms**

navigation, symlink

**Comment by tgodzik** [comment]
Thanks for reporting and the reproduction :heart_eyes: !

If everything is working you can ignore the warning, most likely there is some logic that doesn't follow symlinks.

**Comment by tgodzik** [comment]
Confirmed that Metals doesn't work well with symlinks - Bloop manages to compile everything alright, but we don't translate the links well.

**Comment by aldtid** [comment]
Great, thank you for confirming it!

**Comment by aldtid** [comment]
Is there any plan to fix this issue in next releases?

**Comment by kpbochenek** [comment]
Let us take a look and see if it is something easily fixable :crossed_fingers:

**Comment by aldtid** [comment]
Great, thank you.

**Comment by kpbochenek** [comment]
So we get request for:
`/github/others/sbt-project-with-symlinks/entities/example-entity/core-piece/src/main/scala/com/example/Launcher.scala`
and we call .toAbsolutePath and get:
`/github/others/sbt-project-with-symlinks/pieces/core-piece/src/main/scala/com/example/Launcher.scala`

our workspace is: `/github/others/sbt-project-with-symlinks/entities/example-entity`

that's why we require semanticdb to be here(relative to workspace root):
`/github/others/sbt-project-with-symlinks/entities/example-entity/.bloop/corePiece/bloop-bsp-clients-classes/classes-Metals-zW7pjnPKSb-unn7NCA4LpQ==/META-INF/semanticdb/../../pieces/core-piece/src/main/scala/com/example/Launcher.scala.semanticdb`

but semanticdb is not resolved to absolutepath and is here:
`/github/others/sbt-project-with-symlinks/entities/example-entity/.bloop/corePiece/bloop-bsp-clients-classes/classes-Metals-zW7pjnPKSb-unn7NCA4LpQ==/META-INF/semanticdb/core-piece/src/main/scala/com/example/Launcher.scala.semanticdb`

As @tgodzik said we resolve symlinks to absolute path that end up having different path than bloop semanticdb is and we have mismatch.

It might require asking a question if AbsolutePath is necessary and would we be okay with unresolved one - which is hard question.

**Comment by aldtid** [comment]
I see. What if bloop would check if a directory is a link and avoid the absolute path call when creating and looking for the semanticdb? In order to resolve something like, for example:
`/github/others/sbt-project-with-symlinks/entities/example-entity/core-piece/../../../pieces/core-piece/src/main/scala/com/example/Launcher.scala`
as:
`/github/others/sbt-project-with-symlinks/entities/example-entity/core-piece/src/main/scala/com/example/Launcher.scala`
just by following the symlink without trying to handle its real path.
