### ISSUE TITLE
Add an ability to go to super class/method

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1416]
**Is your feature request related to a problem? Please describe.**
This is well know feature that might be useful for a lot of users. 

**Describe the solution you'd like**
We already look recursively to find the top class in the ImplementationProvider, we could reuse to just go one level up. 

This could be implemented using code lenses although still not sure how it should look exactly. 

If anyone is interested in contributing this feature please let me know. 

**Describe alternatives you've considered**
Search by hand

**Additional context**
Suggested by @olafurpg 

**Search terms**:
Implementation super method class

**Comment by tgodzik** [comment]
@kbochenek is taking a look at this! :tada:

**Comment by kpbochenek** [comment]
UI considerations:

![Screenshot 2020-02-12 at 12 35 48](https://user-images.githubusercontent.com/10478402/74331561-3cdf7f00-4d94-11ea-8ea8-60b0034d6348.png)

^^ This is how it could look like

Even though you can specify a Range in a line where codeLens should be displayed it is always aligned to left. Multiple codeLenses are separated by "|" and aligned to left.
That's why for now I added method name to codelens.

Implementations considerations:
`find the top class in the ImplementationProvider` works only for methods/fields, for classes it needs to be changed or implemented separately. Actually for classes it might be much easier, just jump to `parent` from semanticdb.

Definitely might be cool to implement those methods to go to super method/class and allow user to bind them to keyboard shortcuts, not sure if this would not bloat UI too much with lenses?
Will try to attach screenshot with more realistic class
