### ISSUE TITLE
Metals doesn't work at all

### ISSUE THREAD

**Issue by tampler** [scalameta/metals#1482]
I don't see anything working for my curr project on Ubuntu 18 and VSCode 1.42.1 with Metals 0.8.1

You may check my project here:https://github.com/Neurodyne/zio-arrow/tree/bump-rc18

Thanks,
Boris

**Comment by tgodzik** [comment]
Hey, thanks for reporting. I checked out the project and everything seems to be working. 

Please include more information when reporting an issue, otherwise we will just need to ask for it and everything will take longer. I would also ask that you don't just erase the bug issue template, since it is there so that it's easier for us to solve issues and for the users to provide information.

What exactly isn't working? Did you import the build? In case of any failures they should be in `.metals/metals.log`

**Comment by tampler** [comment]
Pls update that branch again. I purposely added an erroneous Hello World.
I see Bloop finds an error and reports it in output. Metals doesn't see it and displays "No problems" due to the following bug:
```bash
INFO  Connected to Build server v1.4.0-RC1-69-693de22a
INFO  time: imported build in 0.27s
WARN  Could not find java sources in Some(/usr/lib/jvm/java-11-openjdk-amd64). Java symbols will not be available.
INFO  time: indexed workspace in 5.3s
```

I provided a path to the custom Java11 to add support for OpenJdk11. You need to flatmap that value before using internally.

Also adding my log for debug

Best,
Boris
[metals.log](https://github.com/scalameta/metals/files/4300191/metals.log)

**Comment by tgodzik** [comment]
```
WARN  Could not find java sources in Some(/usr/lib/jvm/java-11-openjdk-amd64). Java symbols will not be available.
```

This message just means that the JDK sources are not avaialable on you machine and you will not be able to navigate over them. They are not downloaded automatically in most cases.

> I provided a path to the custom Java11 to add support for OpenJdk11. You need to flatmap that value before using internally.

That message has a Some, but it's because it's just logged using `toString`, java version is properly used in the codebase.

**Comment by tgodzik** [comment]
I also looked into your branch and the issue seems to be with the silencer plugin:

https://github.com/scalameta/metals/issues/1409

I think that got fixed on master in scalameta: https://github.com/scalameta/scalameta/pull/1992
It needs a proper release still.

**Comment by tampler** [comment]
@tgodzik Thanks for your update. So what do I do now? I'm working on a pretty complex project and need a good feedback from VSCode now. 

Currently I'm running sbt from console and fixing in VSCode. That works poorly and needs to be fixed asap

**Comment by tgodzik** [comment]
@tampler Best to disable the silencer plugin when importing from sbt (reenable it later) or work on Scala 2.12.10. The release in scalameta is waiting for someone available to do it, so we cannot promise any timeline there.

**Comment by tampler** [comment]
Alright, moving back to 2.12.10 did a trick. 
Thanks a lot !
