### ISSUE TITLE
Incorrect warning about scala version

### ISSUE THREAD

**Issue by ColOfAbRiX** [scalameta/metals#1548]
**Describe the bug**
After the upgrade to 0.8.3 I keep seeing a warning notification message on the bottom right of the window:
```
You are using a legacy Scala version 2.13.0, which might not be supported in future versions of Metals. Please upgrade to Scala 2.12.11.
```
and this is clearly incorrect (my project uses scala 2.13.0 and the warning tells me to "upgrade" to 2.12.11).

**To Reproduce**
I'm not sure. I'm using Metals 0.8.3, VSCode 1.41.3, Windows 10, SBT 1.3.8.
My build.sbt file is a pretty long multi project file and I ended up trying:
```
scalaVersion := "2.13.0"
Global / scalaVersion := "2.13.0"
ThisBuild / scalaVersion := "2.13.0"
```
but that made no difference. I don't see or find anything unusual in the output logs.

**Expected behavior**
This warning shouldn't appear as my Scala version is higher than the recommended one

**Screenshots**

**Installation:**
- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.8.3

**Comment by ckipp01** [comment]
Thanks for reporting! It looks like the `deprecatedVersionWarning` def in `Doctor.scala` is pulling in the wrong recommended Scala version. It looks like the "recommended" Scala version we are pulling in by default is just `BuildInfo.212`. I'll post the relevant code/locations below incase someone wants to grab this since it should be a quick fix.

**Doctor where the message is formed**
https://github.com/scalameta/metals/blob/68cd1c945768f38b168cb03319649201d62831bd/metals/src/main/scala/scala/meta/internal/metals/Doctor.scala#L174-L190

**Where we grab the version from**
https://github.com/scalameta/metals/blob/68cd1c945768f38b168cb03319649201d62831bd/metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala#L27

**Comment by tgodzik** [comment]
I do already change it in the Scala 3 PR, so I might move it from there or maybe we can wait until it's merged?

**Comment by ckipp01** [comment]
Ahh, perfect. We can probably just wait for that branch to merged _unless_ we are going to cut a release before then? What do you think?

**Comment by tgodzik** [comment]
We would want to release before we merge it most likely. The Scala 3 support would be 0.9.0 in my book. I will move it to a separate PR then.

**Comment by ColOfAbRiX** [comment]
Thank you guys!
