### ISSUE TITLE
”No build targets” for Scala with maven

### ISSUE THREAD

**Issue by riax** [scalameta/metals#1586]
We can't get Metals to work for a project using Maven and Scala. I found an example repository online that has the same problem.

**To Reproduce**
1. Clone https://github.com/codecov/example-scala-maven
2. Open with VS Code
3. Import the build
(Do manual install mvn ch.epfl.scala:maven-bloop_2.10:1.4.0-RC1-162-888454e1:bloopInstall -DdownloadSources=true)
4. Run metals doctor

**Behavior**
”⚠️ No build targets were detected in this workspace so most functionality won't work.”

**Expected behavior**
The project loads correctly

**Comment by tgodzik** [comment]
Thanks for reporting! Not all Scala plugins are supported by Bloop and Metals. Currently Metals supports: https://davidb.github.io/scala-maven-plugin/usage.html

I would suggesting switching to this Scala plugin, since I cannot promise if a support for any others will be available any time soon. 

More info here: https://scalacenter.github.io/bloop/docs/build-tools/maven

And here: https://scalameta.org/metals/docs/build-tools/maven.html

**Comment by tgodzik** [comment]
Closing this, since it seem that a wrong Maven plugin is used here. Let us know if that is not the actual issue.
