### ISSUE TITLE
Auto-import fails to find project type when there are errors

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#1638]
**Describe the bug**
When referencing a new type from the project, prior to import, the type cannot be resolved. This is expected.

![image](https://user-images.githubusercontent.com/74843/79571736-509fae00-8081-11ea-986f-432ae445e82b.png)

Normally we then hit <kbd>Ctrl</kbd>+<kbd>Space</kbd> and get suggestion(s), but instead nothing is found.

![image](https://user-images.githubusercontent.com/74843/79572055-e76c6a80-8081-11ea-9b92-2817c26979cd.png)

Yet, when searching for the type, the project environment _does_ know about it.

![image](https://user-images.githubusercontent.com/74843/79572144-0c60dd80-8082-11ea-8a6c-f5e068d848e1.png)

**To Reproduce**
Cannot reproduce test case, but it's a common occurrence.

**Expected behavior**
Find the type, since it's clearly possible, like any external dependencies.

![image](https://user-images.githubusercontent.com/74843/79571868-8b094b00-8081-11ea-8e5a-ebdab50c6ca9.png)

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.4

**Search terms**
auto, import, complete, auto-complete, autocomplete, auto-import, autoimport, find, type, reference

**Comment by tgodzik** [comment]
Thanks for reporting! I believe this does happen for me too from time to time. Not 100 % sure what is the reason. We'll need to experiment with this a bit.

**Comment by olafurpg** [comment]
The reason why workspace/symbol can know about it is that it’s powered by the mtags index while the presentation compiler (completions,...) needs classfiles. The way auto-imports work is that we query workspace/symbol and then try to load the SemanticDB symbol with the presentation compiler (which fails since the classfiles don’t contain that symbol yet)

**Comment by olafurpg** [comment]
It’s possible to synthesize compiler symbols without classfiles but we risk showing false positives in that case: displaying symbols that are not valid in that build target, workspace/symbol returns results for all classpath a.

**Comment by nilskp** [comment]
> It’s possible to synthesize compiler symbols without classfiles but we risk showing false positives in that case: displaying symbols that are not valid in that build target, workspace/symbol returns results for all classpaths.

Personally, I would prefer that trade-off. The worst thing that happens is a compiler error afterwards, which is my own fault.

**Comment by tgodzik** [comment]
I will close this one in favour of https://github.com/scalameta/metals/issues/917 - that should fix the issue at hand and I don't think we can make the change to allow imports for things that do not compile. It would be especially difficult because we depend on the compiler for a number of functionalities related to imports (like for example shortening them). 

Do let me know if anyone disagrees with this assessment.
