### ISSUE TITLE
No run/debug hover over main, no modules in Metals tab

### ISSUE THREAD

**Issue by nsadeh** [scalameta/metals#1650]
**Describe the bug**

As of today I suddenly don't see any of my modules under the project drop down in the Metals tab and the run/debug button in the App implementation isn't there anymore.

I tried restarting everything short of removing and reinstalling Metals but nothing has worked. Logs look normal.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.8.4

**Additional context**

**Search terms**

**Comment by tgodzik** [comment]
Thanks for reporting! We are working on fixing some recent issues we are having and this might be showing up in your workspace.

Is there anything about semanticDB or deduplicating compilation in the logs? There should be some kind of indication of what is happening.

This issue is most likely due to connection to Bloop, you could try running `Metals: Connect to build server` or `Metals: Restart Bloop server`, which might help.

**Comment by nsadeh** [comment]
Just happened again tonight.

I think  found something in the logs:

```
ERROR code navigation does not work for the file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/src/main/scala/sandbox/Main.scala' because the SemanticDB file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/.bloop/cats-sandbox/bloop-bsp-clients-classes/classes-Metals-ybyJOXSdTPa4oFHtxlVg2A==/META-INF/semanticdb/src/main/scala/sandbox/Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. 
```

Restarting bloop server did not fix this. Neither did deleting the bloop folder/re-importing the project or anything of the sort.

`sbt bloopCompile` gives `java.lang.IllegalStateException: Fatal programming error: bloop session task state is accessed even though the compile state is empty, please report this error upstream.`

**Comment by tgodzik** [comment]
> `ERROR code navigation does not work for the file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/src/main/scala/sandbox/Main.scala' because the SemanticDB file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/.bloop/cats-sandbox/bloop-bsp-clients-classes/classes-Metals-ybyJOXSdTPa4oFHtxlVg2A==/META-INF/semanticdb/src/main/scala/sandbox/Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. `

We use semanticDB files, which are produced during compilation for indexes. If the compilation failed and the old artifacts are not available then some of the things like renames, lenses and references will not work until the files are compiled again. Was there any compilation errors in your workspace maybe?

So this might be the case. It's especially problematic if you open a broken workspace, since the first compilation fails. Other things like complitions, hovers and diagnostics should work OK.

I am not sure what `sbt bloopCompile` does, so I wouldn't use that really.

**Comment by nsadeh** [comment]
This keeps spontaneously happening mid-development. Not sure how to reproduce/what I am doing wrong. Is there an issue with keeping multiple extensions of App?

**Comment by tgodzik** [comment]
This should happen only if you are compiling a workspace from scratch or when you first compiled it after opening a project that contained compilation errors. This will cause the semanticDB file no to be available for that file. Is there anything like that happening?

Not sure if we will be able to fix it soon without a reliable reproduction. As workaround, you could create a `launch.json` configuration and run with F5 independent of the code lenses. It would be something like:

```
    {
      "type": "scala",
      "request": "launch",
      "name": "My main class",
      "mainClass": "foo.Main",
      "args": [],
      "jvmOptions": []
    }
```

and you can just run it as soon as it is compiled.

**Comment by nsadeh** [comment]
Still getting ERROR code navigation does not work for the file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/src/main/scala/sandbox/Main.scala' because the SemanticDB file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/.bloop/cats-sandbox/bloop-bsp-clients-classes/classes-Metals-Crjy_ww3QiiZ4_t0_C8UBQ==/META-INF/semanticdb/src/main/scala/sandbox/Main.scala.semanticdb' doesn't exist. There can be many reasons for this error. 


I have recompiled several times successfully with sbt but haven't managed to get Metals working on VSCode yet. Switching back to IntelliJ until this is fixed.

**Comment by tgodzik** [comment]
> Still getting ERROR code navigation does not work for the file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/src/main/scala/sandbox/Main.scala' because the SemanticDB file '/Users/nsadeh/Desktop/scala-pet-projects/scala-with-cats/cats-sandbox/.bloop/cats-sandbox/bloop-bsp-clients-classes/classes-Metals-Crjy_ww3QiiZ4_t0_C8UBQ==/META-INF/semanticdb/src/main/scala/sandbox/Main.scala.semanticdb' doesn't exist. There can be many reasons for this error.

Was the code compiled for sure? I think we can improve it to always start the full compilation of the workspace, which I don't think we do properly currently. However, I am not sure if we have enough data to fix your issue here specifically.

What was the exact situation where you were getting those warnings? I have only seen it happen in cases where the workspace wasn't compiled for the first time. The issue I see here could be:
- workspace wasn't fully compiled or had an error in it hence the warnings 
- Metals/Bloop were never able to compile the workspace - which would be a realy issue
- semanticDB files were not produced, but code compiled

If it's the first one, then it's the current behaviour. We use semanticDB file for a lot of our indexes. We can for sure improve it by loading even old semanticDB files from the previous compilation, but then the code would still need to be compiled at least once before.

If the issue is one of the latter, we would need to have some more information on this. Maybe a full log or a workspace that this can be reproduced in.

But the biggest question is whether the workspace was really compiled successfully. We could maybe try to confirm that by compiling via Bloop CLI. The easiest to do it would be via coursier:

`coursier launch ch.epfl.scala:bloopgun-core_2.12:1.4.0-RC1-211-fe37baa7 -- compile --verbose root`

**Comment by tgodzik** [comment]
We just released new Metals version with a new embedded Bloop version, which might help with some existing issues. However, we cannot really help unless we get some more information. 

I am closing this, since there is no response to the last comment and we were never really given any actionable information. We can reopen the issue if we get some more data.
