### ISSUE TITLE
"Implement all members" ignores access modifier

### ISSUE THREAD

**Issue by nilskp** [scalameta/metals#1759]
**Describe the bug**
When a concrete class has unimplemented members, the quick fix to "Implement all members" ignores any access modifier, generally `protected` (and instead adds an `override`).

**To Reproduce**
Self explanatory.

**Expected behavior**
Keep the intended access modifier, and preferably not add the semantically inaccurate `override`.

**Additional context**
Personally I dislike having `override` for methods that don't, strictly speaking, override.
But it's a matter of style, so it would be nice to have that as an optional setting.

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm it's an issue. @ckipp01 Any idea how are would it be to fix this?

**Comment by olafurpg** [comment]
Thank you for reporting! Please open a separate feature request to discuss the `override` keyword since it's unrelated to the missing access modifier.

The missing access modifier is a bug in "override def" completions (which is used by "implement all members". A minimal reproduction

```scala
class Foo {
  protected def bar = 42
}
class Bar extends Foo {
  def bar@@
  // currently becomes:   override def bar: Int = ???
  // should become:       override protected def bar: Int = ???
}
```

![2020-05-18 10 48 50](https://user-images.githubusercontent.com/1408093/82205086-855b8b00-98f5-11ea-9d27-24cba0e2cbf0.gif)


>  Self explanatory.

In the future, please take the time to provide a minimal example since it makes it much easier to understand the issue.

**Comment by nilskp** [comment]
@olafurpg 

> Please open a separate feature request to discuss the override keyword

Done:
https://github.com/scalameta/metals-feature-requests/issues/126
