### ISSUE TITLE
Ammonite support proposal

### ISSUE THREAD

**Issue by alexarchambault** [scalameta/metals#1766]
**Is your feature request related to a problem? Please describe.**

This describes a possible implementation of Ammonite support for metals, in order to gather comments / opinions.

Adding this feature would involve changes in both Ammonite and metals, so it's better to ensure everyone is onboard on both the Ammonite and metals side before proceeding. If everyone agrees with the idea here, I (@alexarchambault) could manage to work on it from the Scala Center.

**Describe the solution you'd like**

See goals below.

**Describe alternatives you've considered**

Worksheets are a possible alternative, yet don't cover the same use cases as Ammonite scripts. We propose here to have metals handle Ammonite `.sc` scripts, offering the same kind of experience as e.g. sbt projects.

**Additional context**

This is related to https://github.com/scalameta/metals-feature-requests/issues/62. We propose to work on a way to address https://github.com/scalameta/metals-feature-requests/issues/62.

cc-ing @lihaoyi (Ammonite author), @Baccata (who did some groundwork around Ammonite and bloop / metals)

**Search terms**:

Ammonite, scripts, worksheets

**Comment by lihaoyi** [comment]
You guys are correct that in order for any sort of proper code navigation, we need to make the Ammonite script running semantics less dynamic than it currently is.

Currently, any script can have multiple stages, and any upstream script that evaluates can mangle compilation flags and other things to affect downstream scripts. I do not believe many people actually want this functionality, so we can and should get rid of it since it is hindering things we do want.

There are a few things we can do to reduce dynamism:

1. Add statically-analyzable magic imports for common tasks like scala compiler flags or adding repositories. Probably 99% of people tweaking these things do not need dynamic configuration, and would be happy with an `import $scalacOptions` or `import $repositories`.

2. A second option would be to change Ammonite's evaluation model

    1. rather than having every script run sequentially and possibly mangling the compiler state for downstream scripts, we could discover the entire `import $file` graph statically, find all scripts, and compile and run them all together.

    2. To make (2.i) above work, we would need to expose some configurability: we could do this by allowing magic `predef{...}` blocks that are also statically discovered during script discovery, and compiled/executed before the main aggregate script code is compiled/executed. If the code in these `predef{...}` blocks is sufficiently simple/fast, we could even re-run it every time we want to analyze the code without any real issue.

Essentially, approach (2.) above would turn Ammonite's evaluation model from the messy sequential-mutable thing it is now into a five-stage process:

1. Walk the graph of `import $file`s, pick up all relevant scripts
2. Parse out all `predef{...}` blocks in all scripts
3. Compile and run all `predef{...}` blocks, which may set compiler flags and such
4. Compile all scripts
5. Run all scripts

This would allow IntelliJ to easily cut in after step 3 to do its own thing, Metals to cut in after step 4, an Ammonite-scripts-to-jar tool to cut in after step 4, and everyone gets what they want.

Mill should be identical to Ammonite with a slightly tweaked code wrapper. We can ignore it, if we do a good job with Ammonite scripts then Mill will trivially sort itself out.

**Comment by alexarchambault** [comment]
2.i. is already underway I think, with the new script processing stuff added in https://github.com/lihaoyi/Ammonite/pull/1053. (Or did you mean something else, @lihaoyi?) It's just only used via BSP for now, as it lacks the ability to run scripts. The choice would be more between 1. and 2.ii., to handle scalac options, repositories, …

I agree 2.ii. would be neat. But 1. and 2.ii. can complement each other, with 1. as a default, and 2.ii. when 1. can't work. I fear 2.ii. would complicate things when it's not necessary: 1. only relies on parsing, while 2.ii. needs parsing / compiling / running, which takes more time.

**Comment by lihaoyi** [comment]
Yes you're right, that's exactly what I meant. The only difference would be I'd like to make it not just a side-codepath for doing analysis, but instead the primary codepath for all scripts. That would both simplify things, avoid divergence between analysis and execution, and also give benefits around compilation speed, packaging, and possibly incremental compilation.

You are right that 1. and 2.ii complement each other. We can have both, no need to pick and choose. Right now we have both `interp.load.ivy` that can be called inside a multi-stage script and also `import $ivy` for the common case where the user does not need any dynamism, and a similar split for repositories, scalac options, and other things would fit right in
