### ISSUE TITLE
Please document how to run stuff

### ISSUE THREAD

**Issue by japgolly** [scalameta/metals#1807]
Hi! I'm trying to figure out how to {run,debug} Scala {apps,tests} with Metals and I can't figure it out. From memory there used to be a little link that would appear when you hover over things but I'm not seeing it anymore. I've reimported, restarted, run the Metals Doctor which tells me everything is A-OK, and finally I've been going through all the documentation and it's not mentioned at all.

It'd be very helpful if the documentation were updated to include instructions on running stuff.

Thanks!

**Comment by tgodzik** [comment]
Thanks for reporting! Normally you either run things two ways:
- via code lenses, which appear over main/test classes - if they don't appear it might be due to JRE being used by Bloop (this can be checked via Bloop CLI `bloop about`), compilation issues or it might be a new bug.
- via json configuration in VS Code that looks like:
```
    {
      "type": "scala",
      "request": "launch",
      "name": "tests.SymlinkedProjectSuite",
      "testClass": "tests.SymlinkedProjectSuite"
    },
    {
      "type": "scala",
      "request": "launch",
      "name": "Sources",
      "mainClass": "scala.meta.internal.metals.JdkSources",
      "args": [],
      "jvmOptions": []
    }
```
and it can be specified in the run side bar. It also actually auto completes with the default Scala configuration or we will have a wizard open up if there is no configuration and someone tries to run something.
This is the standard VS Code way to run things. In coc-metals we use the vimspector, but I am not 100% sure about the details. And we can also run/debug in emacs.

It could be useful to document as much as possible on the website. I will take a look into it once doing the new release. The code lense issue is a separate one, so we should take a closer look at it.
