### ISSUE TITLE
Deleted Code Handled Improperly

### ISSUE THREAD

**Issue by jrduncans** [scalameta/metals#1814]
**Describe the bug**
After deleting a file, instead of being able to recompile and find the error referencing the deleted code, the original code still tries to be referenced, and then throws a `ava.nio.file.NoSuchFileException` because the file is missing.

**To Reproduce**
1. Delete a file
2. View a file that referenced deleted code
3. Hover over deleted type reference
4. See exception in logs
5. Attempt recompiling, no change
6. Attempt restart server, no change

**Expected behavior**
Code referencing deleted code would update to show as a compilation error

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.0
- Metals VSCode extension version: v1.9.0

**Comment by jrduncans** [comment]
The only way I was able to get it to work correctly was to remove all the directories (but not the top-level .json files) inside of the .bloop directory.

**Comment by tgodzik** [comment]
Thanks for reporting! I think this is being caused by the fact that the previous artifact are still present in case of a failed compilation. This causes the presentation compiler to pick those artifacts, since they are on the classpath.

What compilation error was being shown in this case?

I will try to dig in and see if we can handle such situations better.

**Comment by tgodzik** [comment]
I am unable to reproduce the issue. Once a file is deleted and we save an another file (or manual trigger compilation) everything gets recompiled and a proper error is shown.

What we can fix for sure is make sure that the FileNotFoundException is not being thrown.
