### ISSUE TITLE
Support sbt files

### ISSUE THREAD

**Issue by tpolecat** [scalameta/metals#1838]
It would be helpful if Metals supported `.sbt` files … I have no idea how hard this would be but I didn't see an issue for it so here you go :-)

Thanks as always for your hard work.

**Comment by tgodzik** [comment]
In the end https://github.com/scalacenter/bloop/pull/1297 will most likely not get merged due to reasons specified by @jvican  We need to get to the approach with mutiple build connection, which we already do for Ammonite. This should be simpler though, since we are always conencting to the same build server.

@dos65 Will be taking an another stab at it. Please let us know if you encounter any issues. I've already seen that you are on the right track with the previous PR.

**Comment by dos65** [comment]
I've reworked my previous PR in metals - #1865 . Now it works over multiply BSP connections.
But it anyway depends on scalacenter/bloop#1219
