### ISSUE TITLE
why does metals doesn't support .sc

### ISSUE THREAD

**Issue by abhishekvaid** [scalameta/metals#1868]
Scala worksheet extension is ".sc". It's supported by intelliJ and new dotty scalaIDE. Why does metals insist on renaming sheets to .worksheet.sc

**Comment by kpbochenek** [comment]
Worksheets are not official scala component. There is no 'worksheet standard' to call it. We implemented it long time ago this way, others implemented it differently. Theoretically even available syntax in worksheets might be slightly different.
Extension was chosen to be `*.worksheet.sc` and that stayed with metals.

It turns out that was a good choice because right now we also have ammonite scripts that have `.sc` extension and are different from worksheets.

Also `dotty scalaIDE` was done to provide initial syntax support for dotty team and will be removed when metals will supersede scalaIDE features.

**Comment by olafurpg** [comment]
Thank you for reporting! Ammonite script support was released last week, see release notes https://scalameta.org/metals/blog/2020/07/01/lithium.html#ammonite-support 

Please open a new ticket if you encounter issues with the Ammonite support
