### ISSUE TITLE
Update docs for emacs how to install metals

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#1884]
>  olafurpg left a comment
> 
> Thank you for this contribution! I see that our Emacs docs still recommend coursier bootstrap when there is a better alternative coursier install metals-emacs, which can be updated with coursier update metals-emacs. It might be worth updating the documentation to recommend this setup at some point

**Comment by kczulko** [comment]
Good morning @kpbochenek,

Please beware that some users might want to add some java-opts like e.g. trustStore path/pass (which happened to me). Since general `coursier install` channel obviously isn't configured with custom options, it would be nice to mention about that within the updated docs with advice what to do such case (I assume that not all of us know `coursier` in depth - e.g. I don't know :) ).

In comparison to predefined channel json (https://github.com/coursier/apps/blob/master/apps/resources/metals-emacs.json) the bootstrap installation steps make it obvious where to pass additional params:
```
  ./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=emacs \
  --java-opt -Djavax.net.ssl.trustStore=<path>
  --java-opt -Djavax.net.ssl.trustStorePassword=<pass>
  org.scalameta:metals_2.12:0.9.2 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals-emacs -f
```

Best regards,
Karol

**Comment by tgodzik** [comment]
Updated in https://github.com/scalameta/metals/pull/2733/files
