### ISSUE TITLE
Multiproject doesn't recognised as a project by metals plugin

### ISSUE THREAD

**Issue by marcraminv** [scalameta/metals#1890]
**Question**

A module with no `.scala` files but using `.sc` should be recognised as a project in the packages section?

I have followed this structure https://github.com/pbassiner/sbt-multi-project-example but the modules only appears in the packages menu if there are `.scala` files.

**Screenshots**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/13021787/86439046-0df88400-bd08-11ea-8d7a-f6e7e2bc109f.png">
<img width="290" alt="image" src="https://user-images.githubusercontent.com/13021787/86439058-13ee6500-bd08-11ea-924d-cc75c7c14b94.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.9.1

**Comment by tgodzik** [comment]
Thanks for reporting! This is the intended behavior. Since no artifacts are produced for the module and there is nothing to show, we don't want to add an empty node. 

The code is here:
https://github.com/scalameta/metals/blob/4920adc4e870b957cbea2fa999f723ccdc3622fe/metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala#L66

**Comment by marcraminv** [comment]
My fault not unfold the packages. But inside the `articles`, `books`, etc there are `whatevername.worksheet.sc` files, but are not recognized as a project. I understand that this is not behaviour expected.

**Comment by tgodzik** [comment]
Worksheets are not compiled, but evaluated. This means they do not produce any artifacts that can be displayed. You can even have the same class defined in each worksheet, because each worksheet is a separate entity. We will not be able to display them properly in the packages view.

The packages view is used to look over the structure of the code classes, objects etc. Worksheets are not a part of that so they cannot be displayed.
