### ISSUE TITLE
Import suggestions aren't deduplicated

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1900]
**Describe the bug**
The quick fixes for importing symbols can contain duplicates. In large files, this can result in way too many options spanning more than a single screen can fit.

**To Reproduce**
1. Write some code that needs an import to work
2. Write it twice
3. Select it all and open quick fixes (cmd+. on mac)
4. See duplicate import suggestions

**Expected behavior**
Suggestions are deduplicated before being shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/894884/87192957-e8ffa480-c2f7-11ea-860e-736d8d5ffe09.png)

![image](https://user-images.githubusercontent.com/894884/87192964-ebfa9500-c2f7-11ea-8f46-e3957ecfdead.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.1 / extension version 1.9.1

**Search terms**
Import, duplicated, duplicate, dupes, dupe, auto import

Update: Nice ticket number!

**Comment by tgodzik** [comment]
Thanks for reporting! I can confirm the issue, the problem is that we translate each error to a new code action. We shouldprobably group by the message here:

https://github.com/scalameta/metals/blob/48b20201f3357738ce472c40dcae47b0cccc56fb/metals/src/main/scala/scala/meta/internal/metals/codeactions/ImportMissingSymbol.scala#L52

**Comment by kubukoz** [comment]
I suppose that would be more useful than deduplicating just the suggestions, but also more expensive (since there's more information in a diagnostic, and also more diagnostics than just missing imports). Do you think it'll have a heavy impact?
