### ISSUE TITLE
MAVEN_OPTS/JAVA_OPTS/.jvmopts/Server Properties has no effect on mvn run

### ISSUE THREAD

**Issue by strowk** [scalameta/metals#1923]
**Describe the bug**
All possible ways of passing proxy configurations from environment are completely ignored

**To Reproduce**
1. Configure MAVEN_OPTS with socksProxyHost and socksProxyPort
2. Run vscode 
3. Try to import the maven build in Metals
4. See errors indicating that proxy is not used

**Expected behavior**
Should use socks proxy.

**Screenshots**

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v1.9.1

**Additional context**
I have to use socks proxy to connect to proper Maven repository. I was always using MAVEN_OPTS to configure that and AFAIK there's no other way to do it in Maven. With Intellij Idea there was no problem to set env variable and also I could just download deps first via mvn dependency:resolve, because Intellij also uses ~/.m2 , but it seems that Metals does not.
Is it possible maybe to configure Metals to just use ~/.m2 ?

**Comment by strowk** [comment]
Also tried http proxy instead with JAVA_OPTS, .jvmopts , "Server Properties". None of them works. 
JAVA_TOOL_OPTIONS had some effect - it now logs in output "Picked up JAVA_TOOL_OPTIONS: -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=28080", but long after "Downloading from", which means that it does not work at all. No way to configure proxy :(

**Comment by strowk** [comment]
What worked eventually is this 
```
    <proxies>
        <proxy>
            <id>local-proxy</id>
            <active>true</active>
            <protocol>http</protocol>
            <host>127.0.0.1</host>
            <port>28080</port>
        </proxy>
    </proxies>
```
in settings.xml, but it only works on http proxy (I can only use socks5, but I can and had to configure second one http->socks5). 
Maven does not support configuring socks5 via settings.xml and to avoid running http to socks5 proxy, I think Metals should respect and pass MAVEN_OPTS

**Comment by tgodzik** [comment]
Thanks for reporting! `MAVEN_OPTS` should be available if you run VS Code from console with `MAVEN_OPTS` defined. Otherwise Metals server doesn't have it available.

Alternatively, you can run the import manually via `mvn ch.epfl.scala:maven-bloop_2.12:1.4.3:bloopInstall -DdownloadSources=true`. More information is available [here](https://scalameta.org/metals/docs/build-tools/maven.html).

You can also specify a separate `mvn` script that defines all the needed data and change maven script in the user configuration.

We could also try to add the properties from  `.jvmopts` or `Server Properties` when running Maven, but not sure about it.

**Comment by strowk** [comment]
I'm running vscode in Windows, from start menu. I think it should have all envs available (MAVEN_OPTS is configured in "Edit the system environment variables"). 

Regarding ".jvmopts or Server Properties", I've been reading this - 
https://scalameta.org/metals/docs/editors/vscode.html#http-proxy

And it says that .jvmopts, JAVA_OPTS  and "Server Properties" should work for HTTP proxy with maven:

> Metals uses Coursier to download artifacts from Maven Central. To use Metals behind an HTTP proxy, configure the system properties -Dhttps.proxyHost=… -Dhttps.proxyPort=… in one of the following locations

Is this documentation still up to date?

**Comment by strowk** [comment]
Well, I've been trying to use sbt for the project, but at the time I was using Intellij Idea, which works really good with maven, but with sbt it was creating some unnecessary folders and gave a lot of weird errors, so after some discussion we decided to drop sbt and I had impression, that most of the projects are using maven, because it's so much better supported in general. Seems like metals is a part of a different ecosystem :)

**Comment by tgodzik** [comment]
Maven is perfectly fine, it is indeed used, maybe not really rarely, which was my impression. According to the survey [here](https://www.jetbrains.com/lp/devecosystem-2019/scala/) around 38% of people used it. Sbt has some nice features useful for Scala development, but it might not be needed everywhere. 

Anyway, I am trying to do some fixes for the Maven integration as much as the time allows. It's a good thing you found this one! We are happy to receive both issues and contributions.

**Comment by LeUser111** [comment]
Hi! I'm unfortunately giving up on Metals for now. I've tried to import a maven project for many hours now and it just won't work due to ignoring any and all proxy settings I've provided!

My setup is really simple: There's a proxy running on localhost:3128 without any authentication requirements.

The environment variables http_proxy, https_proxy, HTTP_PROXY and HTTPS_PROXY are configured correctly. That should be enough imho!

In addition, to install Metals, I've had to set 
-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 
in the VSCode settings (each value in a separate line).

With that I could install Metals itself. 

Unfortunately things got really bad from there:

Build import did not work because both the environment and the VSCode settings were ignored. Ultimately I've now set the following variables:
`
-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost
`
in:
Environment: 
* JAVA_OPTS
* JVM_OPTS
* MAVEN_OPTS

Files: 
* ~/.jvmopts
* ~/.bloop/.jvmopts 
* vscode_workspace/.jvmopts
* vscode_workspace/.bloop/.jvmopts

None of that was enough to perform a full build import. I've also tried using my own maven installation, which was able to install another part of bloop or its dependencies but now I'm ultimately stuck with 
`2022.02.10 07:33:57 WARN  Stopped configuration of Scala SemanticDB in 2.13.3 projects: Error downloading org.scalameta:semanticdb-scalac_2.13.3:4.4.32
  not found: /home/.../.ivy2/local/org.scalameta/semanticdb-scalac_2.13.3/4.4.32/ivys/ivy.xml
  download error: Caught java.net.ConnectException: Connection refused (Connection refused) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.3/4.4.32/semanticdb-scalac_2.13.3-4.4.32.pom
`
and I don't even know where that is coming from (is that a message from Metals? Or Bloop?) 

This is very frustrating, to be honest! It's like whack-a-mole - whenever I find a setting that get's picked up by some element of Metals, some other component gets downloaded that chooses to ignore all previous settings again!

I really appreciate what you are working on with Metals and I'm glad you've chosen to support Maven. But there are currently just too many hoops to jump through for a single proxy setting.

**Comment by tgodzik** [comment]
@LeUser111 I am very sorry that you haven't managed to set Metals up and seems you were very close. We need to handle things much better, but I haven't managed to work on it yet.

I think what needs to be done here is to add `-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128` to `.bloop/bloop.json`  as described in https://scalacenter.github.io/bloop/docs/server-reference#custom-java-options

What should actually happen is to add that automatically, since user should not need to be aware of the fact that Bloop is used underneath.

**Comment by LeUser111** [comment]
@tgodzik Thank you very much for your reply! I've incorporated the setting you suggested and the installation proceeded another step :) It's now running into another issue, but I have yet to take a closer look at it (and time is extremely short these days -.- ).

In any case I'd gladly test an improved setup. Should we choose to use metals, I'd also have to set it up for several colleagues and provide a simple step-by-step guide for our internal environment. So any simplification is welcome!

**Comment by tgodzik** [comment]
I am fixing the main problem behind this issue in https://github.com/scalameta/metals/pull/3662

I will also be working on making sure proxies and mirrors are working currently, starting with https://github.com/scalameta/metals-vscode/pull/899 

The main issue we need to address is https://github.com/scalameta/metals/issues/2485

**Comment by tgodzik** [comment]
@LeUser111 the new coursierMirror setting should be available in the prerelease version. Please let me know if it it helps. In the meantime I am looking into some other potential fixes.

**Comment by LeUser111** [comment]
@tgodzik I've finally found the time to evaluate Metals again :) The experience is _much_ smoother now - thank you :)

We are still having minor issues with build imports (Metals 0.11.6):
* On my PC the maven-wrapper now seems to use the Maven Settings (~/.m2/settings.xml), however it does not seem use ~/.mavenrc which includes the path to the CA certificate used by our repository 
* On my colleague's PC, the maven-wrapper did not use the Maven Settings and instead ran into a timeout
* In both cases, a manual install via `mvn ch.epfl.scala:maven-bloop_2.13:1.5.0-18-003e6c7b:bloopInstall -DdownloadSources=true` worked well

It's likely that my PC contains left over configurations from my previous installation attempt. We will try to find out what the current default behavior is with a third PC.

**Comment by tgodzik** [comment]
@LeUser111 you can specify which maven scrupt to run in the Metals settings `metals.mavenScript`.

**Comment by LeUser111** [comment]
@tgodzik Ah yes, of course. I had missed it somehow - now everything works like a charm! That is awesome :) Thank you :)
