### ISSUE TITLE
Dependency problem with lib folder

### ISSUE THREAD

**Issue by joncard1** [scalameta/metals#2082]
**Question**

I am running VS Code with a multi-home project, and only one of those homes is a Scala project with a build.sbt file. It has some jar files in the "lib" folder within that home. When the sbt starts properly, it compiles, but the editor does not acknowledge those libraries. I get an error in the import statement: "object ____ is not in package ____". Is there a way to set the CLASSPATH of the editor other than putting the jar into the local mvn repo? Is there project structure that would work better?

**Installation:**

- Operating system: Mac
- Editor: Visual Studio Code
- Metals version: v1.9.3

**Search terms**

jar, library, editor

**Comment by joncard1** [comment]
I seem to have solved it by adding the lib folder to the project.classpath value in .bloop/scala.json and .bloop/scala-test.json. Not sure why I had to change both, and not sure if there is a UI way to do it.

**Comment by tgodzik** [comment]
Thanks for reporting! After adding a jar to lib directory you should rerun build import, which can be done via a command in the command palette or button in the Metals view.

There might be some issues with multiple roots due to https://github.com/scalameta/metals-feature-requests/issues/87 so if you are still having issues I would recommened opening the directory with sbt in a separate window.

**Comment by tgodzik** [comment]
Closing this for now, let me know if you have any more questions.

**Comment by joncard1** [comment]
Thank you for responding. I’m sorry I missed your original reply and I’ll try your recommendation if it happens again.
