### ISSUE TITLE
Valid Dotty code leads to syntax error coming from the scalameta parser when first opening a file

### ISSUE THREAD

**Issue by smarter** [scalameta/metals#2094]
I don't know what the scalameta parser is for, but until it supports Dotty it would be nice to have an option to turn it off.

**To Reproduce**

1. Open any file using Dotty indentation syntax
2. Observe syntax errors
3. The errors go away when you start typing (assuming the build import succeeded)

**Expected behavior**

No spurious syntax error.

**Screenshots**

![](https://gitlab.epfl.ch/lamp/cs210/-/raw/master/labs/images/syntax-error-bug.png)

**Installation:**

- Operating system: all of them
- Editor: Visual Studio Code
- Metals version: v0.9.4

**Additional context**

This is the second most confusing things about using metals for students (the most confusing thing is https://github.com/scalameta/metals/issues/1683)

**Comment by tgodzik** [comment]
Thanks for reporting! That is indeed an issue, it's connected to https://github.com/scalameta/metals/issues/1653 and I planned on working on it at the same time. The problem is that before connecting to Bloop we are loading up the presentation compiler for Scala 2, which detects issues in the code as it is not Scala 2 syntax.
