### ISSUE TITLE
Compiling without saving the buffer?

### ISSUE THREAD

**Issue by suicide** [scalameta/metals#2217]
**Question**

Is there a way to get coc-metals to compile code that was not saved to disk but exists in the buffer? 

I have been using coc-tsserver and coc-java for the last couple of months and they seem to compile/inspect the changed code from the current buffer in nvim. Did I miss something in the config to achieve the same behavior?

**Comment by suicide** [comment]
>  well I guess this is also a bit opinionated though correct? 

Sure it is :D. However, since tsserver and java have such behavior it might be weird for some others at first, too.

> So a compilation would have needed to be triggered. Do you know if a compilation is triggered with coc-java in order to get a diagnostic in this situation, or is it with some sort of semantic parsing the engine is picking this up?

So I did a quick trace in coc-java... and it also sends each keystroke to jdt.ls with a 'textDocument/didChange' and immediately sends a 'textDocument/completion'. After that the client gets multiple 'language/progressReport' notifications on validate documents, publish diagnostics, and building. Inbetween the client gets the actual diagnostics with 'textDocument/publishDiagnostics'.

The diagnostics are shown after I return to normal mode. I do not know if this is an actual compilation?
I could attach a trace log if you want me to.

**Comment by olafurpg** [comment]
@suicide the current diagnostics behavior is an intentional choice. See 11:50 in this talk here for more details https://www.youtube.com/watch?v=MRQMylDxBJ8

I agree it requires a different workflow but having using it for a long time now I find it quite annoying when I use language servers that publish diagnostics as I type. When I’m editing an incomplete program I find the diagnostics distracting. 

In Scala, you also have macros that can report diagnostics and can have non-trivial performance overhead. For simple programs it’s certainly possible to type-check on every keystroke but the UX quickly deteriorates as the codebase grows in size.

**Comment by suicide** [comment]
@olafurpg That is actually a great explanation! Thank you for that. It also explains why syntax errors are being shown before I save a file.
