### ISSUE TITLE
Bloop warning being shown when no build import was done but `.bsp/sbt.json` exists.

### ISSUE THREAD

**Issue by phdoerfler** [scalameta/metals#2341]
## Describe the bug

Metals complains about a missing bloop build after starting up, see **Exhibit A**.

It can also be provoked independently of the import question by telling it to connect to a running build server, see **Exhibit B**.

No connection to the build server is established and Metals does thus not provide any apparent functionality that would require a build definition.

### metals.log

```text
2020.12.25 23:27:47 INFO  Started: Metals version 0.9.8 in workspace '/Users/phi/Documents/workspace/Scala/MetalsBug' for client vscode.
2020.12.25 23:27:49 INFO  time: initialize in 1.5s
2020.12.25 23:27:49 INFO  Attempting to connect to the build server...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/jw/6060chfn35bb7_4l_1w3ss0h0000gn/T/bsp-launcher14851760122142146247/bsp.socket'...
Waiting for the bsp connection to come up...
2020.12.25 23:27:49 WARN  no build target for: /Users/phi/Documents/workspace/Scala/MetalsBug/build.sbt
[0m[32m[D][0m Waiting for a connection at local:///var/folders/jw/6060chfn35bb7_4l_1w3ss0h0000gn/T/bsp-launcher14851760122142146247/bsp.socket...
The server is listening for incoming connections at local:///var/folders/jw/6060chfn35bb7_4l_1w3ss0h0000gn/T/bsp-launcher14851760122142146247/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2020.12.25 23:27:50 INFO  tracing is enabled: /Users/phi/Library/Caches/org.scalameta.metals/bsp.trace.json
2020.12.25 23:27:50 INFO  time: connected to build server in 0.27s
2020.12.25 23:27:50 INFO  Connected to Build server v1.4.6-15-209c2a5c
2020.12.25 23:27:49 ERROR Empty build targets. Expected at least one build target identifier.
2020.12.25 23:27:49 ERROR Empty build targets. Expected at least one build target identifier.
2020.12.25 23:27:49 ERROR Empty build targets. Expected at least one build target identifier.
2020.12.25 23:27:53 INFO  time: indexed workspace in 3.5s
2020.12.25 23:27:53 WARN  no build target for: /Users/phi/Documents/workspace/Scala/MetalsBug/build.sbt
2020.12.25 23:27:53 INFO  no build target: using presentation compiler with only scala-library
```

## To Reproduce

1. Visual Studio Code is closed.
2. Run this in a terminal outside of Visual Studio Code in the directory of your project:

```zsh
foreach s (.bsp .metals .bloop .vscode .DS_Store target metals.sbt) echo "Deleting $s…"; fd --hidden $s --exec rm -rf {}; end
```

3. If you want to be extra thorough:

```zsh
rm -rfv ~/.sbt/boot ~/.sbt/preloaded # Very optional
```

4. fwiw I happen to have no global sbt settings. In particular, I do not have this set:

```
Global / semanticdbEnabled := true
```

I don't know if it affects anything but felt it necessary to point out since sbt recommends enabling the setting:

```
[warn] Metals requires the semanticdb compiler plugin
[warn] consider setting 'Global / semanticdbEnabled := true' in your global sbt settings ($HOME/.sbt/1.0)
```

but https://scalameta.org/metals/blog/2020/11/06/sbt-BSP-support makes no mention of it.

5. start `sbt`:
```
[info] welcome to sbt 1.4.5 (N/A Java 15.0.1)
[info] loading settings for project global-plugins from sbt-errors-summary.sbt,sbt-updates.sbt ...
[info] loading global plugins from /Users/phi/.sbt/1.0/plugins
[info] loading project definition from /Users/phi/Documents/workspace/Scala/MetalsBug/project
[info] loading settings for project metalsbug from build.sbt ...
[info] set current project to scratchpad (in build file:/Users/phi/Documents/workspace/Scala/MetalsBug/)
[info] sbt server started at local:///Users/phi/.sbt/1.0/server/473b095c179e4dd7e355/sock
[info] started sbt server
sbt:scratchpad>
```

6. Start Visual Studio Code and open this directory. I have done so via `code .`
7. Metals will offer you to import the build, along with an error, shown in **Exhibit A**.

## Expected behavior

It should not show an error.

## Installation

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: 0.9.8
- Extension version: v1.9.10
- sbt version: 1.4.5 (N/A Java 15.0.1)

## Further information

If, despite the error, Metals is instructed to attempt to generate a bsp configuration for the build tool, after a few moments, a warning is shown as can be seen in **Exhibit C**, indicating that navigation would not be working.

This is the generated `sbt.json` (after formatting):

```json
{
  "name": "sbt",
  "version": "1.4.5",
  "bspVersion": "2.0.0-M5",
  "languages": [
    "scala"
  ],
  "argv": [
    "/usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home/bin/java",
    "-Xms100m",
    "-Xmx100m",
    "-classpath",
    "/var/folders/jw/6060chfn35bb7_4l_1w3ss0h0000gn/T/metals1547539892474703038/sbt-launch.jar",
    "xsbt.boot.Boot",
    "-bsp"
  ]
}
```

### Exhibit A
<img width="582" alt="image" src="https://user-images.githubusercontent.com/163428/103138299-5e5a0880-46d1-11eb-96ff-7a476517b23c.png">

### Exhibit B
<img width="622" alt="image" src="https://user-images.githubusercontent.com/163428/103134880-9acb3b80-46b4-11eb-84ed-f6cc9e1ee0b9.png">

### Exhibit C
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/163428/103142894-27551880-470c-11eb-886d-59902a34efa5.png">

### Directory Structure
```
tree -a
.
├── build.sbt
├── project
│  ├── build.properties
│  └── project
└── src
   └── main
      └── scala
         └── Scratchpad.scala
```

### build.sbt

```
name := "scratchpad"
ThisBuild / organization := "io.doerfler"
ThisBuild / version := "1-SNAPSHOT"
ThisBuild / scalaVersion := "2.13.4"
```

### Scratchpad.scala

```
object Scratchpad extends App {
  println("hello")
}
```

### project/build.properties

```
sbt.version=1.4.5
```

**Comment by phdoerfler** [comment]
I have finished editing the issue and it's ready for someone to take a look at.

**Comment by tanishiking** [comment]
@phdoerfler  Thank you for reporting and attaching a detailed reproducible example!

The popup `Missing valid Bloop build in ...` in `Exhibit A` shows up if there's no `${project-root}/.bloop` which should have build configuration for bloop. 

If you click `Import build` in `Exhibit A`, metals invoke sbt to run `sbt bloopInstall` and generate build configuration for bloop in `.bloop`, then `Empty build target` error in metals.log should disappear :)

And, you can confirm metals detected all build targets by running `> Metals: Run doctor`.

![Screen Shot 2020-12-26 at 15 23 57](https://user-images.githubusercontent.com/9353584/103146572-fbc74200-478e-11eb-8e03-5118bd2e19f0.png)

By the way, if you wanna use the sbt build server instead of bloop, you can `> Metals: switch build server` and select `sbt`. (if there's `.bsp/sbt.json` which is generated by [sbt server](https://github.com/sbt/sbt/blob/b8dac523386310d52efa71e04b443970539327d0/protocol/src/main/scala/sbt/internal/bsp/BuildServerConnection.scala))

**Comment by tanishiking** [comment]
Ah, I was out of the context (the conversations on discord https://discord.com/channels/632642981228314653/632652693013528589/792059375698968647) and didn't realize you are using java 15.

I tested your example with **java 11** both with BSP of sbt and BSP of bloop and it works fine, but not yet tested with java 15.

**Comment by ckipp01** [comment]
Thanks for the detailed write up @phdoerfler. I've been able to pinpoint when exactly this happens and also reproduce it. Mainly, irregardless of the Java version I can reproduce this _only_ if there is an existing `.bsp/sbt.json` file present without every importing the build yet. With this in mind, there are a couple things I'd like to clarify in your points.

> I don't know if it affects anything but felt it necessary to point out since sbt recommends enabling the setting:

Can you explain when you see this warning? There are multiple ways to use sbt BSP with metals--either you use the `generate-bsp-config` command or the `bsp-switch` command. Both which will include the `metals.sbt` file including the `sbt-metals` plugin, which will set this value for you and ensure that correct options are all set. Meaning you shouldn't see your warning. You seeing the warning makes me feel like somehow in your case with neither of those commands being utilized, the plugin isn't getting included.

It's also important to remember, as outlined in the blog post you linked, Metals favors Bloop. Without an explicit choice to use sbt in Metals, it will default to Bloop. So in the situation where you use the `build-connect` command, you're not actually telling it to connect to the running sbt server, but rather since no choice was made, it's connecting to bloop, and as @tanishiking pointed out, since there wasn't an import done, it warns you.

All that to say, there is an actual issue here. Namely, if a `.bsp/sbt.json` file exists _before_ you ever open a project, and you open it, Bloop shouldn't be showing the warning. There was some work done on this in https://github.com/scalameta/metals/pull/2297 to ensure that in your exact scenario it didn't auto-connect to sbt, but there seems to still be something missing causing the warning.
