### ISSUE TITLE
Search library dependencies doesn't work

### ISSUE THREAD

**Issue by mikkka** [scalameta/metals#2346]
Search library dependencies doesn't work in VSCode 1.52.1 Metals 0.9.8 Bloop 1.4.6

**To Reproduce**

1. Open project with cats dependencies
2. Search for some type class (just for example Parallel) from cats (cmd+T `Parallel`)
3. It can be found in `.metals/readonly/cats/Parallel.scala`
4. You may use to search for other symbol, it's not clear to me what can be placed and searched in `.metals`
5. Try to search it in libraries (cmd+T `Parallel;`)
6. It can't be found, nothing can be found in libraries

**Expected behavior**

One can search in libraries for symbols with addition of `;`

**Installation:**

- Operating system: macOS 10.15.7
- Editor: Visual Studio Code 1.52.1
- Metals version: v0.9.8

**Comment by tgodzik** [comment]
Thanks for reporting it seems that using `;` is not working currently properly. However, I am not exactly sure what is happening, so I would need to dig in a bit more.

**Comment by kpbochenek** [comment]
Isn't it correct that `Parallel;` cannot be a symbol therefore no results is expected behavior?

When metals wants to redirect user to a file from library it gets file from source jar, puts it in `.metals/readonly/` directory and requests VSCode to display it. Any file from dependencies that has sources can land in `.metals/readonly`

**Comment by olafurpg** [comment]
I think VS Code recently changed the behavior so that it no longer displays workspace/symbol results that don’t “match” the query string according to VS Code. I recently noticed this issue myself, it’s also not possible to do nested package searches like “j.i.File”. 

I’m not sure what is the best solution except to report issues upstream. I opened several issues in the past that were focused on preserving results unchanged from the server

**Comment by mikkka** [comment]
I've tried a few last versions of vscode, it's broken in each of them.

**Comment by ckipp01** [comment]
So I'm not 100% sure what to do with the issue. Trying all these example out in non-vscode editors seem to work as expected. Even the `j.i.File` example shows me exactly what I want.


https://user-images.githubusercontent.com/13974112/121873083-4a00db00-cd06-11eb-8d8a-afabda40df6a.mov

I don't believe there is a whole lot that we can do on the Metals side for this since it's actually an issue that lies with VS Code.

**Comment by olafurpg** [comment]
For the record, the semicolon syntax is a hack that Metals uses because LSP has no equivalent to the select box in IntelliJ that allows you to filter results by “this project”, “dependencies” or “everywhere”. 

One feature that is actually missing in Metals is allowing text search through dependency sources. An example usecase would be to search for application.conf of upstream dependencies. But my understanding of this issue is that we’re talking about symbol search (implemented by Metals, not supported by VS Code) instead of text search (not part of LSP)
