### ISSUE TITLE
java.lang.NoSuchMethodError: sbt.Keys$.reresolveSbtArtifacts()Lsbt/SettingKey;

### ISSUE THREAD

**Issue by babysnakes** [scalameta/metals#2371]
**Describe the bug**

Starting today (probably because I pulled some code that required reload) a play framework project I'm working on fails to load with the above error (I'll attach the full log at the end of the message). This is not because of the change, resetting the project doesn't change anything. I have other scala projects using mostly the same plugins, scala version, sbt version and they all load fine. The main difference is that this is play framework project with submodules (I can't think of anything else). I can't even run plain `sbt` unless I delete all the generated `metals.sbt` files.

**To Reproduce**

Sadly I can not refer to the project as this is a work project. I will happily answer any question you have that does not requires me to reveal code.

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.9.10
- sbt version: 1.2.8

**Additional context**

The log:

[metals.log](https://github.com/scalameta/metals/files/5782083/metals.log) (EDIT: please ignore the first error in the log file, not sure what command I ran to cause this error)

Thanks in advance
(and thank you for creating this project so I can avoid working in Intellij)

**Comment by tgodzik** [comment]
Thanks for reporting! The issue you encountered is caused by caused by sbt-bloop plugin needing to use a setting that was only added in 1.3.0. You should be fine with using the `1.4.6` version of the plugin or updating sbt to 1.3.0. We also handle it in Metals since https://github.com/scalameta/metals/pull/2350 That was not yet released,, but you should be able to use a recent snapshot https://scalameta.org/metals/docs/editors/overview.html#latest-metals-server-versions

**Comment by babysnakes** [comment]
Wow, that was fast 😄. 

Thanks a lot.
