### ISSUE TITLE
"Error downloading org.scalameta:semanticdb-scalac_2.12.13:4.4.2"

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/metals#2395]
**Describe the bug**

Metals install sbt-metals, which prevents users from using `semanticdbVersion` setting.

**To Reproduce**

1. Use Metals on an sbt build, which creates `project/metals.sbt`
2. Next, update the build to Scala 2.12.13, set `ThisBuild / semanticdbVersion := "4.4.6"` and launch sbt
3. compile

**Expected behavior**

It compiles. Ideally Metals should be released with the support of the latest Scala versions. If not, it should not prevent the users from using `ThisBuild / semanticdbVersion := "4.4.6"` setting.

**Screenshots**

```
[error] (utilInterface / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.13:4.4.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/eed3si9n/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.13/4.4.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.13/4.4.2/semanticdb-scalac_2.12.13-4.4.2.pom
[error]   not found: /Users/eed3si9n/.m2/repository/org/scalameta/semanticdb-scalac_2.12.13/4.4.2/semanticdb-scalac_2.12.13-4.4.2.pom
[error]   not found: https://dl.bintray.com/sbt/maven-releases/org/scalameta/semanticdb-scalac_2.12.13/4.4.2/semanticdb-scalac_2.12.13-4.4.2.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.12.13/4.4.2/semanticdb-scalac_2.12.13-4.4.2.pom
[error]   not found: https://dl.bintray.com/hedgehogqa/scala-hedgehog/org.scalameta/semanticdb-scalac_2.12.13/4.4.2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scalameta/semanticdb-scalac_2.12.13/4.4.2/ivys/ivy.xml
```

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.8

**Additional context**

https://github.com/scalameta/metals/blob/31c711a1e8879ec4f852f1b6cc48223b39bdb284/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala#L18-L21

**Comment by tgodzik** [comment]
Thanks for reporting! I am still working on adding the support for 2.12.13, had a number of unexpected issues along the way. As soon as it's released it should work alright. 

Unfortunately, `ThisBuild / semanticdbVersion := "4.4.6"` will not help users even if they set it themselves, since there is no actual support for Scala 2.12.13 in Metals yet. I think it's better that Metals does control the version used, since we usually keep the newest one.

Biggest problem here is that it's taking me so long to release now :/

**Comment by eed3si9n** [comment]
I'm not sure if I was clear in the report, but one of the problems is that Metals is adding a plugin locally on my disk _AND_ it rewires ` semanticdbCompilerPlugin` key at the project-level as opposed to using `semanticdbVersion` at the Global-level, which prevents me from compiling even when I'm _not_ using Metals, and the error state is not obvious that it's happening because of the plugin.

My current workaround is take back the `semanticdbCompilerPlugin` key to default by re-rewiring the key in all subprojects:

```scala
  semanticdbCompilerPlugin := {
    ("org.scalameta" % "semanticdb-scalac" % semanticdbVersion.value)
      .cross(CrossVersion.full)
  },
```

**Comment by tgodzik** [comment]
Hmm.. we might need to use `semanticdbVersion` when it's set then. 

@ckipp01 do you think it makes sense - use  `semanticdbVersion` when it's set otherwise use the Metals set version?

**Comment by ckipp01** [comment]
Thanks for pointing this out @eed3si9n!

Just to clarify in case anyone happens to stumble onto this later, this _only_ happens when using sbt as a BSP server. This would all still be valid if using the defaults (bloop).

> @ckipp01 do you think it makes sense - use semanticdbVersion when it's set otherwise use the Metals set version?

I think the tricky part is that if we do a simple check to see if it's set, it will always be set since the `SemanticdbPlugin` sets it. So in order for that to work, we'd have to know if a user set it vs if the plugin set it. Couldn't we just instead do similiarly to what the `SemanticdbPlugin` does here:

https://github.com/sbt/sbt/blob/600942303f4c92d1d170b5ad0d512eb8fe836864/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L25-L30

And just add in the `semanticdbVersion` as a global setting, and then read it from the `projectSettings`? Then if a user overrides it, it will be picked up? Or is there another solution that you think would be better @eed3si9n?

I'll try to play around with this today.
