### ISSUE TITLE
Unable to inspect when debugging object extending App trait 

### ISSUE THREAD

**Issue by chrisbarker** [scalameta/metals#2482]
**Bug**
I can't inspect variables when I hit a breakpoint in an object which extends the App trait.

1. Set break point in code
2. Run debugger
3. Hit breakpoint
4. Unable to inspect variables

**Expected behavior**

I expect to be able to debug and inspect variables in an object which extends the App trait in the same way that I can with an object that implements a main entry point.

**Screenshots**
Expected
<img width="789" alt="Screen Shot 2021-02-06 at 1 37 18 PM" src="https://user-images.githubusercontent.com/1299463/107126890-81efa180-6880-11eb-9772-65485dac4747.png">
Bug
<img width="789" alt="Screen Shot 2021-02-06 at 1 37 41 PM" src="https://user-images.githubusercontent.com/1299463/107126896-86b45580-6880-11eb-9159-5af31d05635d.png">

**Installation:**

- Operating system: Linux - Ubuntu 20.04.2 LTS

- Editor: Visual Studio Code v1.53.0
- Metals version: v1.9.13

**Search terms**
debug debugging inspect

**Comment by tgodzik** [comment]
Thanks for reporting! The behaviour is expected. The values in an object are not really local values due to have App trait works, which is why they are not shown in the second example. You should still be able to see them in `this` value:

![image](https://user-images.githubusercontent.com/3807253/107213009-146e7d00-6a08-11eb-9019-2d53e55061e1.png)

**Comment by chrisbarker** [comment]
I can't see them in `this` This is what I see. New project using seed, then open proj folder in vscode and import project into metals, then debug. 
**This** is not expandable to see variables it contains

<img width="706" alt="Screen Shot 2021-02-11 at 4 43 18 PM" src="https://user-images.githubusercontent.com/1299463/107702691-9c62ba00-6c88-11eb-9557-b9ec7bbc5a7b.png">

**Comment by tgodzik** [comment]
It seems I can confirm this in a clean project. Not exactly sure why, the static variables shouldn't actually be currently seen unless we specify an additional setting, which however I did not set.

So what is unexpected is that it works in my case. We would really need to specify the additional setting `showStaticVariables` here:

https://github.com/scalacenter/bloop/blob/6e43cbfda8c67ea96a9595f6d768f4b5f8d2874b/frontend/src/main/scala/bloop/dap/DebugServer.scala#L33

though I worry about providing too much information really. I think it would better to add expression evalautor that would just allow to see it on demand.

**Comment by tgodzik** [comment]
Och, I think it may be the Scala version. It does work for me on 2.12.13, but doesn't on 2.13.4.  What version are you using @chrisbarker ?

**Comment by chrisbarker** [comment]
@tgodzik 2.13.4

<img width="706" alt="Screen Shot 2021-02-12 at 10 28 27 AM" src="https://user-images.githubusercontent.com/1299463/107787483-23fa0880-6d1d-11eb-8996-84a18a42c731.png">

**Comment by tgodzik** [comment]
Och yeah, that fits. Though why it's happening on 2.13.4 is a mystery to me :O

**Comment by adpi2** [comment]
Since 2.13.x the fields of Scala objects are represented by static fields in bytecode (https://github.com/scala/scala/pull/7270). It's the same in Scala 3.

So maybe you are right @tgodzik, we should enable the `showStaticVariables` setting. And if there is too much noise in it we can always filter...

**Comment by tgodzik** [comment]
I am not sure if I ever managed to check if it work with that option. I got kind of confused with the different Scala versions. Did you manage to confirm that it helps here?

**Comment by adpi2** [comment]
I confirm that the `showStaticVariables` works as expected. It shows the object fields, the trait fields and `MODULE$` (that is synthetized by the compiler).

Here for instance, in an object extending `App`:
![image](https://user-images.githubusercontent.com/13123162/121680774-3bbe7f00-caba-11eb-9271-33d790230e92.png)

`MODULE$` is a recursive reference to `this` (not very useful):
![image](https://user-images.githubusercontent.com/13123162/121680903-66103c80-caba-11eb-8aff-102edfeae100.png)

`executionStart`, `scala$App$$_args` and `scala$App$initCode` are coming from the `App` trait:
![image](https://user-images.githubusercontent.com/13123162/121681639-5ba27280-cabb-11eb-9ef2-62bcaf59a841.png)

It is okay to show them but we should find a proper name for `scala$App$$_args` and `scala$App$initCode` as requested in https://github.com/scalacenter/scala-debug-adapter/issues/38. They have weird names because they are private in a trait.

**Comment by tgodzik** [comment]
I think we can turn it on by default and make the names nicer later on. It's better to have more info and in this case Scala usage of static members is more prevalent than in Java I think.
