### ISSUE TITLE
Metals code navigation not working without an error in logs. 

### ISSUE THREAD

**Issue by abhishekvaidprophecy** [scalameta/metals#2488]
Code navigation is not working for a scala project. 

**To Reproduce**
clone this repo and start in vscode 
```
git clone https://github.com/DivLoic/kafka-application4s.git
cd kafka-application4s
code .
```

**Expected behavior**
Code navigation should work.

**Screenshots**

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.9.13

**Additional context**

I'm using openjdk

**Comment by ckipp01** [comment]
Thanks for the report @abhishekvaidprophecy, I just pulled this down locally to test, and the first thing that catches my eye is that the project doesn't fully compile:

```
❯ bloop compile (bloop projects)
Compiling root (11 Scala sources)
[E] [E3] src/main/scala/fr/ps/eng/kafka/app4s/common/package.scala:12:51
[E]      type BASE64Encoder is not a member of package sun.misc
[E]      L12:   val Base64Encoder: BASE64Encoder = new sun.misc.BASE64Encoder()
[E]                                                    ^^^^^^^^^^^^^^^^^^^^^^
[E] [E2] src/main/scala/fr/ps/eng/kafka/app4s/common/package.scala:12:22
[E]      not found: type BASE64Encoder
[E]      L12:   val Base64Encoder: BASE64Encoder = new sun.misc.BASE64Encoder()
[E]                                ^^^^^^^^^^^^^
[E] [E1] src/main/scala/fr/ps/eng/kafka/app4s/common/package.scala:5:8
[E]      object BASE64Encoder is not a member of package sun.misc
[E]      L5: import sun.misc.BASE64Encoder
[E]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[E] src/main/scala/fr/ps/eng/kafka/app4s/common/package.scala: L5 [E1], L12 [E2], L12 [E3]
Compiled root (1245ms)
[E] Failed to compile 'root','root-test'
```

This will cause some issues since semanticdb won't be fully produced, which will cause issues with navigation.

Also as a heads up, but defaults `sun` packages are actually ignored by Metals. If you are using them, you may want to remove it from the exclude list as you can see here: https://scalameta.org/metals/docs/editors/vim.html#excluded-packages
