### ISSUE TITLE
Compilation error on Scala 3 macro not reported

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#2550]
**Describe the bug**

1. Create a Scala 3 project with sbt
2. Open it with Metals using sbt BSP server
3. Create a macro definition with an error in it:

EDITED:
```scala
import scala.quoted._

inline def printCode(inline expr: Any): Unit = ${printCodeImpl('expr)}

def printCodeImpl(expr: Expr[Any])(using ctx: Quotes): Expr[Unit] =
  import quotes.reflect.Position
  '{ println("") }

def foo: String = xxx
```

**Expected behavior**

The error is correctly sent by sbt to Metals but it is not reported by Metals on the source file.

```
// bsp.trace.json

[Trace - 09:45:23 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///home/piquerez/demo/src/test/scala/demo/Foo.scala"
  },
  "buildTarget": {
    "uri": "file:/home/piquerez/demo/#demo/Test"
  },
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 7,
          "character": 2
        },
        "end": {
          "line": 7,
          "character": 3
        }
      },
      "severity": 1,
      "source": "sbt",
      "message": "Not found: xxx"
    }
  ],
    "reset": true
}


[Trace - 09:45:23 PM] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "79",
    "parents": []
  },
  "eventTime": 1614199523154,
  "message": "Compiled demo-test",
  "status": 2,
  "dataKind": "compile-report",
  "data": {
    "target": {
      "uri": "file:/home/piquerez/demo/#demo/Test"
    },
    "errors": 1,
    "warnings": 0,
    "time": 205
  }
}
```

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Comment by ckipp01** [comment]
Thanks for reporting @adpi2! So I'm actually unable to reproduce this locally 🤔 I've tried editing a couple things first and then going back to it, just opening straight up to it, etc and every time it does seem to display:

```
[Trace - 08:15:32 AM] Sending notification 'textDocument/publishDiagnostics'
Params: {
  "uri": "file:///Users/ckipp/Documents/scala-workspace/scala3-test/src/main/scala/Main.scala",
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 5,
          "character": 2
        },
        "end": {
          "line": 5,
          "character": 5
        }
      },
      "severity": 1,
      "source": "sbt",
      "message": "Not found: xxx"
    }
  ]
}
```

<img width="729" alt="Screenshot 2021-02-25 at 08 16 51" src="https://user-images.githubusercontent.com/13974112/109117098-d7152980-7741-11eb-865b-ed840c6f223d.png">

The only thing I notice different is that I don't have the `reset`, but that _shouldn't_ cause it not to be displayed as that triggers a clear before we show the diagnostic.

Are there any other details that may be relevant? sbt version, jdk version, or something else you can think of?

**Comment by adpi2** [comment]
Sorry for this, I minimized the example too much...

You should be able to reproduce with this piece of code:

```scala
import scala.quoted._

inline def printCode(inline expr: Any): Unit = ${printCodeImpl('expr)}

def printCodeImpl(expr: Expr[Any])(using ctx: Quotes): Expr[Unit] =
  import quotes.reflect.Position
  '{ println("") }

def foo: String = xxx
```

The simple fact that there is a quoted expression somewhere in the file seems to mute all the errors inside that file. They are reported by sbt but Metals do not transmit the information to the editor. Instead it prints the following log:

```shell
2021.02.25 10:40:32 INFO  /home/piquerez/adpi2/src/test/scala/macros/Foo.scala:11:19: stale sbt error: Not found: xxx
def foo: String = xxx
                  ^
```

**Comment by ckipp01** [comment]
Ahhh ok cool, I see what you're talking about now @adpi2. Let me dig in and see if I can find out what's going on here.

**Comment by ckipp01** [comment]
So I'm actually surprised we haven't hit on this yet. The issue is actually here:

https://github.com/scalameta/metals/blob/1cff2bb71f06600fe66ae68741bcc98b8b4c42ad/metals/src/main/scala/scala/meta/internal/parsing/TokenEditDistance.scala#L338-L348

When we are making sure that the diagnostics are fresh, we calculate the `TokenEditDistance`. While doing that we are using `Trees.defaultTokenizerDialect`, which is 2.13.

https://github.com/scalameta/metals/blob/1cff2bb71f06600fe66ae68741bcc98b8b4c42ad/metals/src/main/scala/scala/meta/internal/parsing/Trees.scala#L117

So we can't correctly parse that, it fails, and then we return a `TokenEditDistance(no-match)` which makes metals think it's stale.

My original thought is to change that default tokenizer to determine if it's a Scala 2 or 3 source like we do up above in the actual `Trees` class. The tricky part is that we use that default tokenizer in quite a few places that don't have access to the `Trees` class. What is your thoughts on this @tgodzik? I noticed recently we've been passing `Trees` around a bit more to handle this in various places, and maybe we should just get rid of this default tokenizer in the companion object and always force access through `Trees` so that when we tokenize to ensure that we always have the correct handling of choosing the correct dialect. wdyt?

**Comment by tgodzik** [comment]
A quick fix would probably be to use Scala3 as a fallback dialect similar to how I did it in scalamtags. But probably it would be best to pass the correct one in most places. That would need some more refactoring though. We could maybe refactor one usage at a time starting with the more urgent ones?
