### ISSUE TITLE
"Move Class to file" refactoring

### ISSUE THREAD

**Issue by kuberlog** [scalameta/metals#2691]
Given: I have 3 small case classes and a trait in 1 file

When: The case classes grow in size and should be extracted to separate files

Then: I should be able to invoke "Move class to file" refactoring which moves the class out of its current file and into its new one, changing references if the new file is of a new package, auto-imports needed packages in the destination file and deletes unneeded imports in the original file.

**Comment by Giggiux** [comment]
The idea of how we'll try to implement is the following:

We want to support extracting a class from a file if there are multiple classes/case classes definitions (more than 1) via code action.

The code action will be shown only on the name of the classes if the file name is not the same as the "selected" class. This is so because it would mean the class is already in the correct file.

The code action will be shown only if there are multiple classes in the top-level syntax Tree node (this needs to be checked if it holds also for package objects). We don't want to extract inner-classes, nor extract a class in a file without other classes.

The source code will be copied in a new file called as the Class name, using the code from the `Defn.Class` node. 
If a file with the same name already exists, an error will be shown, to make the user realize that maybe they already have a file where that class should be.


Regarding the imports, we will just copy them all, and let the users remove the unused imports vis Scalafix or similars as suggested previously.

**Comment by olafurpg** [comment]
@Giggiux Thank you for sharing! I'm really excited to be able to use this feature. A few comments, feel free to ignore 

> The code action will be shown only on the name of the classes if the file name is not the same as the "selected" class. 

It would be nice if this code action also skipped classes that extend a sealed class that has the name as the file. 

> nor extract a class in a file without other classes.

In this case, it would be nice to have a separate code action to rename the file to match the class name, or rename the class to match the file name :)

> Regarding the imports, we will just copy them all, and let the users remove the unused imports vis Scalafix or similars as suggested previously.

This sounds great! 🙏 The "Move class" refactoring in IntelliJ tends to remove too many imports (for example extension methods) causing the new file to fail compilation.

**Comment by Giggiux** [comment]
@olafurpg Thanks for the suggestions!
Regarding the following:

> It would be nice if this code action also skipped classes that extend a sealed class that has the name as the file.

This is actually a very good suggestion, but it made me thinking:
Shouldn't we skip classes that extend a sealed class/trait, even if those don't have the name of the file?

**Comment by olafurpg** [comment]
@Giggiux that’s a good point. It might also be worth moving subclasses if the user asks to move a sealed class/trait.
