### ISSUE TITLE
JVM left dangling after VScode shutdown

### ISSUE THREAD

**Issue by MRandl** [scalameta/metals#2722]
**Describe the bug**

Metals opens two JVMs when running code, but lets one outlive the VSCode process, ie it just sits around and consumes approximately 300MB of ram

**To Reproduce**

Generate the basic scala 3 project and run it once.
On the activity monitor, sort by memory usage : there are two java process instances. One is the one executing the code (800MB) and one has a use that's unknown to me and uses 200 to 300 MB. The latter does not disappear when vscode leaves, essentially keeping memory from being used by other apps.

**Expected behavior**

Every JVM launched by Metals should be killed when VSCode is closed.

**Screenshots**
In this one, I just quit VSCode :
<img width="1100" alt="Capture d’écran 2021-04-15 à 13 07 20" src="https://user-images.githubusercontent.com/17947709/114860575-783c6a00-9dec-11eb-8ec5-bad7f6bfb2f5.png">

This shows that the JVM is related to Metals in some way, it is running in my metals project directory
<img width="565" alt="Capture d’écran 2021-04-15 à 13 14 37" src="https://user-images.githubusercontent.com/17947709/114860659-9013ee00-9dec-11eb-8e70-f3ffeace3ffb.png">

**Installation:**

- Operating system: macOS & Windows, Linux not tested
- Editor: Visual Studio Code
- Metals version: v0.10.1

**Search terms**

jvm vscode process not killed

**Comment by dos65** [comment]
@MRandl  Thanks for reporting but it's likely an expected behavior

Usually, Metals spawn at least two java process: 
- one is itself - metals LSP server
- the second is `bloop` that stays alive even after closing editor. There is an feature request to fix this thing - https://github.com/scalameta/metals-feature-requests/issues/129

Could you ensure that process you mentioned has `bloop.Server` main class?

**Comment by MRandl** [comment]
okay that's something I didn't know, my bad.
 I'm really down for the feature to optionally kill it !
