### ISSUE TITLE
Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess

### ISSUE THREAD

**Issue by odwrotnie** [scalameta/metals#2741]
It is impossible to run a class on macOS with Silicone M1

**To Reproduce**

1. Go to the class you want to run
2. Click on `run`
3. Look at `DEBUG CONSOLE`
4. See error `Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess`

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v1.10.4

**Comment by tgodzik** [comment]
Thanks for reporting, it seems that nuprocess has not had a release since last year and it seems it might not support it.

We should most likely work on using normal Java process API. There is a feature request connected to this here: 
https://github.com/scalameta/metals-feature-requests/issues/51

To fix this issue you can try to run the import manually via:

`sbt -Dbloop.export-jar-classifiers=sources bloopInstall`

And running the command to connect to server or just reloading the window.

**Comment by tgodzik** [comment]
Och wait, the issue is with run :scream: I haven't seen that one previously :thinking: 

What java version are you using? It seems that maybe Bloop is not starting the JVM process? It might be possible that Bloop is actually using an unsupported Java version. You could make sure it uses the correct one via additional settings:

https://scalacenter.github.io/bloop/docs/server-reference#custom-java-options

**Comment by odwrotnie** [comment]
I tried `openjdk64-16`, `zulu64-11.0.10`, `zulu64-15.0.2`.

**Comment by odwrotnie** [comment]
Update! It started to work with `openjdk 16.0.1 2021-04-20` from `https://jdk.java.net/16/`. Thanks!!!
