### ISSUE TITLE
Multiple main classes found in Scala 3 projects

### ISSUE THREAD

**Issue by kpbochenek** [scalameta/metals#2763]
For scala3 basic project when I try to execute command "run main class in the current file" I get:
![2021-05-02-112423_518x130_scrot](https://user-images.githubusercontent.com/10478402/116808444-0f1d5c00-ab39-11eb-8b8c-68c3aa3078e8.png)

But a file is:
```scala
package com.kpbochenek.scala3

object Main {
  def main(args: Array[String]): Unit = {
    println("Works!")
    println("UH okay")
  }
}
```

Choosing first or second doesn't matter, the same main method is executed. Would be good to get rid of this duplicated entry.
This might be something in metals but noticed it in VSCode that's why reporting it here.

Also it might be needed to do small UI improvement, because "S..." is confusing
it looks better when main package is shorter:

![2021-05-02-112911_506x130_scrot](https://user-images.githubusercontent.com/10478402/116808560-b7cbbb80-ab39-11eb-928b-c033c2d2e295.png)

But maybe this sentence could be in separate line and not truncated when package scope is long, just a concept :)

**Comment by ckipp01** [comment]
Thanks for reporting @kpbochenek, I thought we already had an issue for this, but it looks like not. This happens in general when we search for main classes in the current file. It only happens with Scala 3 so I believe the fix needs to actually happen upstream.

**Comment by kpbochenek** [comment]
Also I think it doesn't work for "current file". It suggests all objects with main in any file present in project.

**Comment by ckipp01** [comment]
> Also I think it doesn't work for "current file". It suggests all objects with main in any file present in project.

So it purposefully doesn't actually target _only_ the file you are in. There is a `testFile` and `testTarget`, but the `run` specifically will search for any mains in the current build target.

**Comment by kpbochenek** [comment]
![2021-05-02-180730_668x70_scrot](https://user-images.githubusercontent.com/10478402/116819741-a8686480-ab71-11eb-85ed-924e88079699.png)

This from VSCode side confused me a little because (taking aside duplicates) it suggests all mains from all files.
If you have a project with multiple files containing main function(for presentation/tutorial purposes) it becomes unusable as you see 10+ choices also from other files.

Initially I thought a duplicate is related to run/debug thing, but it is related to main/test build target?

**Comment by ckipp01** [comment]
> This from VSCode side confused me a little because (taking aside duplicates) it suggests all mains from all files.

Ahh yea I can get how that would be confusing since it says current file. I think that's just a mistake on the VS Code side that should be fixed. For example in the nvim-metals docs you'll see:

> `run` (automatically discovers the main method and runs it for the current
    build target)

https://github.com/scalameta/nvim-metals/blob/494371505cb1b93f41644f34614ad2e2ad498f5b/doc/metals.txt#L846-L847

So a little bit of back story is that I first worked on this because there wasn't code lenses yet in the built-in LSP of NeoVim, so I wanted a quick way to be able to run a main in a build target. Since in normal cases you maybe have one or two, searching the build target for the main ended up working really well because it allowed for you to be anywhere in the target, trigger a run, and still have the code run.

> If you have a project with multiple files containing main function(for presentation/tutorial purposes) it becomes unusable as you see 10+ choices also from other files.

ah yea that's a good point that honestly didn't come up during the review process. Do you think having a `runFile` and `runTarget` might help here?

> Initially I thought a duplicate is related to run/debug thing, but it is related to main/test build target?

Correct, in the situation you mentioned, there will be two listed in here:

https://github.com/scalameta/metals/blob/c6441eb4b16d475f3e930e6784dffcf596edf9ea/metals/src/main/scala/scala/meta/internal/metals/debug/BuildTargetClasses.scala#L158

**Comment by tgodzik** [comment]
That's my bad, I thought that was only in the current file for "run". I guess it would make sense to have 2 parameters now?
```json
{ "runType": "main", "scope": "file"}
```

Or just the additional `runTarget`/`runFile` @ckipp01 suggested?

Alternatively, we could use quick pick here instead of message request? That one is searchable in VS Code, so it's easy to pick up the correct one.

**Comment by kpbochenek** [comment]
Yes definitely updating VSCode action message and changing it to quick pick would be a very nice improvement :+1: 

Another thing is I want most of time to actually re-run last 'action' I realized I used it a lot in Intellij and actually that's what I missed here.

`runFile` would be nice addition if it is not too complicated.

After thinking about it would it be possible to add 'run last action' command? 
I use runTarget/runFile/click on lenses -> and then I can re-run this main by executing 'run last action' ?
This would be perfect because when I work and test using one main method I could run it wherever I want and I don't have to always select main method.

**Comment by ckipp01** [comment]
> runFile would be nice addition if it is not too complicated.

I think this is totally doable. All the logic is already there, so changing the `run` to `runFile` and `runTarget` should be straightforward. 

> After thinking about it would it be possible to add 'run last action' command?

I think this can actually be done on the client side right? I know [nvim-dap](https://github.com/mfussenegger/nvim-dap), which I use for `nvim-metals` actually has some `re-run` functionality that works quite nicely for the exact purpose you mentioned. Actually now thinking about it, I'm not positive how that works when there are _multiple_ mains. I need to check that.

**Comment by tgodzik** [comment]
> > After thinking about it would it be possible to add 'run last action' command?
> 
> I think this can actually be done on the client side right? I know [nvim-dap](https://github.com/mfussenegger/nvim-dap), which I use for `nvim-metals` actually has some `re-run` functionality that works quite nicely for the exact purpose you mentioned. Actually now thinking about it, I'm not positive how that works when there are _multiple_ mains. I need to check that.

Yeah, we would need to add it in the client. Not entirely sure how yet to do it on VS Code side though.

**Comment by kpbochenek** [comment]
Just curious why not keeping it in metals and provide for all clients by default?

When running "run" lenses or 'runFile' / 'runTarget' action metals would persist main that was executed and on new command 'last-action' it would simply run persisted main if present?

**Comment by tgodzik** [comment]
We could do that for sure, it could be something like `"runType": "last"`

**Comment by dos65** [comment]
This one was fixed in [this commit](https://github.com/scalameta/metals/pull/3212/commits/9f615ff0cc192aa091ac9b61cd465a2762359a4e)
