### ISSUE TITLE
Docs static website

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#289]
Following an offline conversation with @olafurpg, we would like to eventually have a static website for the docs. Ideally it would be markdown-based, with some dynamic variables provided during the build.

I've found https://www.scala-sbt.org/sbt-site (which is used by bloop) and it looks quite interesting: you can target several static-site generators, like Hugo or Gitbook and it supports pre-processing for variable substitutions.

@jvican do you have any interesting opinion on this?

**Comment by olafurpg** [comment]
I use sbt-site with gitbook in the metadoc website and it works OK. The preprocessing step in combination with tut is a bit slow for my taste but it does the job and makes it super easy to expose variables from the sbt build. 

Big 😂

**Comment by jvican** [comment]
Both Hugo and gitbook work well as website generators. I'm a big fan of Hugo templates and how easy to hack are. This is not so important for you since I guess you're better off with a predefined theme to save up time.
  
`sbt-site` is excellent. Highly recommended, though I don't recommend using sbt to iterate on your docs. I always make modifications to my docs outside of the build and only use `sbt-site` to publish docs on merge. I think that gitbook has a neat CLI too, so it's easy to make modifications to the docs, you can use that instead of the Hugo CLI if you decide to go for the former. Happy doc'cing!

**Comment by olafurpg** [comment]
Fixed, we have an awesome website now https://scalameta.org/metals/ big thanks @gabro for pushing through on this!

**Comment by gabro** [comment]
We'll eventually want use sbt-docusaurus for this, but so far so good :)
