### ISSUE TITLE
Rename refactoring affects unrelated targets.

### ISSUE THREAD

**Issue by agilesteel** [scalameta/metals#2901]
I created a minimal project to reproduce the issue. Follow the `README.md` here: https://github.com/agilesteel/rename-issue

**Comment by dos65** [comment]
Thanks for reporting! I'm able to reproduce it. That's indeed a bug.

**Comment by tgodzik** [comment]
I think this is due to the fact that we don't list references by target, we would nee to change that. Maybe keep BuildTargetId with the BloomFilter and when starting to check for references keep a set of affected build targets, which would be the ones that include this source file and all downstream that depend on them.
