### ISSUE TITLE
IdentifierComparator will fail with long numbers

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#2960]
**Describe the bug**

It seems that with big projects some of the nodes in three view might have ids that are not representable by int. We should switch IdentifierComparator to use Long or use a separate comparator for TreeView

**To Reproduce**

1. Open a really large project
2. Try clicking around on the tree view

This was reported on discord, though I totally forgot to raise it here.

**Expected behavior**

No exception.

**Installation:**

- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.10.5

**Search terms**

long tree view IdentifierComparator

**Comment by Z1kkurat** [comment]
A bit of clarification: as pointed out in [discord channel](https://discord.com/channels/632642981228314653/632652693013528589/869549202877841459), the problem is in the sorting of the list, namely in `IdentifierComparator` which sorts entries so that `Function10` goes after `Function2` in the list.  
To do that it takes that number substring and tries to convert it to Int which fails. But I don't think that using Long instead will fix the problem, it will just minimize the impact a bit, because in my example it failed when trying to convert a number substring in  `javax.servlet.jsp.jstl-1.2.0.v201105211821.jar` and failed for `201105211821`. There's no prevention from having even longer numeric substring in jar file name which will overflow Long

**Comment by Z1kkurat** [comment]
Here's the illustration of the error for this exact library

![image](https://user-images.githubusercontent.com/7479593/127151702-22092ae9-8d15-4ba8-b2a0-f3aa94b3ceb4.png)
