### ISSUE TITLE
FileWatcher not working for a large project on macOS Big Sur

### ISSUE THREAD

**Issue by pvid** [scalameta/metals#2961]
**Describe the bug**

Recently I started to work on a large SBT project (metals reports 125 build targets + several hundred library dependencies) with a  newly set up Intel MacBook Pro (running Big Sur).

I noticed "rename" and "find all references" did not work most of the time. The strange thing is that sometimes they worked, sometimes they worked for only some projects, the next time they worked for a different subset of projects. It was all a bit non-deterministic.

I have done some debugging and the issue seems to be that `FileWatcher` does not report events for some or most of the projects, which causes the semanticdb files to not be indexed by the `ReferenceProvider`. There is nothing useful in the `metals.log`. I even tried to turn on the `swoval` debug logging and I did not see any errors. However, no events updates were triggered when recompiling subprojects where "find all references" did not work.

I tried to look into the macOS settings and tried to increase the `maxfiles` setting, which was set relatively low. That seems to help a bit, but the problem still occurs. Unfortunately, I don't know much about how file watching on macOS works. Maybe @eatkins of swoval fame could offer some insight - is my computer just terribly misconfigured? Could there be an issue in how swoval and macOS APIs interact when watching a large number of directories?

**To Reproduce**

That is going to be quite hard... I don't know of a open source project with so many subprojects and the behaviour is non-deterministic.

**Expected behavior**

File watching to work reliably or report a clear error in the logs.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.4, v0.10.5

**Search terms**

macos, big sur, file watcher

**Comment by eatkins** [comment]
This kind of thing is very difficult to debug. In the past, I've seen similar behavior when there are too many [file system event streams](https://developer.apple.com/documentation/coreservices/1443980-fseventstreamcreate) created on the machine. There are some libraries that try to interact with the osx file system watcher as though it were inotify and create a stream for every directory in the file system hierarchy. Since inotify handles are _not_ recursive, libraries might naively try to register an event stream for each directory in the file system hierarchy which is what you are required to do on Linux. Unfortunately, this works very badly with OSX and you quickly exhaust what appears to be a system wide limit on file event streams. The swoval library tries to be smart and whenever the application registers a new directory for watching, it checks if the new directory is already in the hierarchy of a directory under monitoring or if there are previously registered directories that are beneath the new directory in the hierarchy. In either case, it consolidates the streams into a single string and closes the redundant streams.

Now, as I mentioned above, I've observed that there is a global limit on the number of event streams though I haven't found any documentation on this from Apple. For this reason, it is possible that another application outside of sbt and metals (which both internally use swoval) is creating file system watchers that are exhausting this limit. For example, before metals switched to swoval, I was having problems where in sbt my system was not triggering on file updates because metals was using a library that used the naive technique that I described above. Without knowing any of the details of your system, it seems possible that some other application (possibly vscode or a plugin) could be creating file watches that are exhausting the system wide limit. I know that there are plugins for vim that create watches using facebook's watchman for example. I don't know of any way to query the OS to determine what programs are holding event streams open but that would be incredibly valuable for debugging if such a thing exists.

Another thing that I could see causing problems is if somehow your project is setup so that there are subprojects that are not in the same directory hierarchy as the root sbt project and/or if the subprojects are using symlinks. I'm a little bit hazy on how swoval handles creating watches on say directories foo/bar and foo/baz. Off the top of my head, I'd expect there to be two streams created for each directory although it could be implemented with a single stream on foo with filters to include results only from foo/bar and foo/baz. In a normal sbt project where all the subprojects are contained in subdirectories of the root directory, it is almost certain that there is only a single stream created since sbt needs to monitor the root directory for changes. As a result, a typical sbt project should only have a single stream open for the root directory (unless there is a bug in swoval that I'm unaware of which). Symlinks are tricky and swoval makes a best effort there but I would not be surprised to find bugs involving them.

The other thing that is possible would be application logic errors in metals or sbt. In sbt for sure there should only be one active global file monitor for the entire sbt process but if there is more than one, then it would be possible that each watcher is making its own streams which would again make it more likely that your system hits the stream limit. To check if this is happening, you could take a heap dump of the metals and sbt processes and look for instances of com.swoval.FileTreeRepositoryImpl.

Regarding the absence of errors in the log, the error reporting for apple file system event streams is abysmal. In older versions of OSX, when you hit the system wide stream limit, you would start seeing stdout or stderr (I can't remember which) flooded with errors about creating a stream but no actual error would be returned by any of the fseventstream api functions. Ever since I think Catalina, you don't see even those error messages anymore, file watching just silently fails. I don't think there is anything that the can be done about that besides filing a bug with Apple.

The one other thing that came to mind as I was writing is that I remember finding a very strange bug in the file events api that I never reported to Apple. If you have two subdirectories where the name of one of the directories is a prefix of the other, then watch wouldn't work. I made an sbt specific workaround to this issue: https://github.com/sbt/io/commit/c210babc6e62e47adeaa86ca15303cae22f2354e but I never addressed it directly in swoval so that's another possible culprit if metals is hitting this issue.

**Comment by tgodzik** [comment]
Maybe we are doing it wrong in Metals? We are doing:
`sourceDirectoriesToWatch.foreach(repo.register(_, Int.MaxValue))`

so maybe we are watching each target/source directory separately and this causes us to quickly run out of the limit.

We could try watching just the workspace and maybe filter anything that is not in the watched directories?

**Comment by eatkins** [comment]
Now that I think about it, I could see how this might be a problem for metals that isn't a problem for sbt. In sbt, as I mentioned, we always watch the base directory so that we can detect if the build files changed. As a result, there will only be one watch stream provided that all of the source directories are children of the project root directory (which I'd imagine is effectively always the case). If the `sourceDirectoriesToWatch` does not include the project root directory, I could see how that could very easily cause the number of watch streams to grow too high.

> We could try watching just the workspace and maybe filter anything that is not in the watched directories?

This is a good suggestion. I think this could be done reasonably efficiently. 

My suggestion would be to update the FileWatcher to have two interfaces for the `restart()` method. The problem is mac specific so the alternate interface would only be used on mac. The new interface would be something like:
```scala
def restart(): Unit = restart(None)
def restart(baseDirectory: Option[Path]): Unit = {
  ...
  // before registering the sourceDirectories, register the baseDirectory
  // the watch doesn't need to be recursive because it is being added purely for the
  // side effect of the file tree repository creating an internal watch stream on the
  // base directory which should cover all of the project source directories provided
  // that all of the source directories are children of the project root.
  // An alternative approach in the event that there are projects that have source
  // directories that are not children of the workspace root directory would be to
  // calculate the common parent(s) of the source directories and create a watch
  // for each common parent. I am assuming though that this is either extremely
  // uncommon or perhaps even unsupported by metals so that this simple
  // solution should do the trick.
  baseDirectory.foreach(repo.register(_, 0))
  sourceDirectoriesToWatch.foreach(repo.register(_, Int.MaxValue))
}
```

Then:
```diff
diff --git a/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala b/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
index 720c30373..d85dd9818 100644
--- a/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
+++ b/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
@@ -2317,7 +2317,9 @@ class MetalsLanguageServer(
       clientConfig.initialConfig.statistics.isIndex
     ) {
       try {
-        fileWatcher.restart()
+        fileWatcher.restart(
+          if (scala.util.Properties.isMac) Some(workspace.toNIO) else None
+        )
       } catch {
         // note(@tgodzik) This is needed in case of ammonite
         // where it can rarely deletes directories while we are trying to watch them
```

The one problem with this approach is that if there are any scala sources in the root directory that metals does not intend to watch/index, then these would probably need to be filtered in the `onChange` callback: https://github.com/scalameta/metals/blob/24ba93875f88a84c0a62d1e0b3c08115bc98c299/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L1276-L1289
The `didChangeWatchedFiles` filters out any files that are not scala or java so the only additional filter I can imagine needing would be one for files in the workspace directory assuming that the workspace directory is _not_ supposed to be monitored. Theoretically the filter could be as simple as: `path.getParent != workspace`.

The other thing that all of this discussion brings to mind is that it might be worth having a watch monitor in metals. If there is a directory that metals knows that it should be able to write to, then it could create a new watch service that monitors that directory. The monitor could periodically wake up, touch a file in that directory and verify that it receives an event within some time frame. If it doesn't, it could assume that watch is broken and periodically poll the filesystem for changes instead. Ideally it would also give the user instructions for submitting a bug report. I'm not volunteering to actually implement it, but I thought it was an idea worth sharing :)

**Comment by tgodzik** [comment]
Thanks @eatkins! It seems a reasonable course of action and shouldn't be a lot of additional work.

**Comment by pvid** [comment]
Hi @eatkins, I dug a little deeper. After reading about similar issues in various node.js project and gradle, I was curious why there are no errors - issues from other project mention errors while registering paths for watching. I noticed that `FileTreeRepository#register` is returning a value that is ignored in metals. However, it always returns a `Right(true)`.

After some fun with the debugger, I found out that the filesystem is returning an invalid stream handle and the `ApplePathPatcher#register` is returning a false, [see](https://github.com/swoval/swoval/blob/develop/files/jvm/src/main/java/com/swoval/files/ApplePathWatcher.java#L111). However, the result is disregarded one level up in `FileCacheDirectoryTree` [here](https://github.com/swoval/swoval/blob/9d62a35fee13872dba7fc1e98e20850880fe2198/files/jvm/src/main/java/com/swoval/files/FileCacheDirectoryTree.java#L417). Even the docstring for `ApplePathWatcher#register` does not mention that it return a `false` in case of registration failure. Should I create an issue in the swoval repository? If the API would surface failures from the filesystem, clients like metals could do a better job reporting issues.

Nevertheless, this addresses only error reporting and not the actual issue with the mac fs 😞 a solution like @eatkins proposed would still need to be implemented

**Comment by eatkins** [comment]
Hey @pvid. Thanks for the investigations! Yes, it would be good to submit an issue in the swoval repository. I wrote the core of swoval more than three years ago at this point, so I can't remember why the FileCacheDirectoryTree disregards the result from the path watcher but I agree that it seems wrong and it would be better to report the issue back to the caller. Fixing the reporting issue may also give more insight into how many streams cause problems. Ultimately this is an apple bug and it should be reported to them but the more detailed the report and reproduction steps, the more likely they are to potentially fix it (though I am a little bit pessimistic that they actually will).

**Comment by pvid** [comment]
I have submitted an issue.

I wouldn't consider a constraint on the number of open FSEvent streams a bug, they should just make it more transparent (and maybe configurable) akin to file descriptors.

**Comment by eatkins** [comment]
That's a fair point since it never is a good idea to treat any resource as infinite but like you said, they should be transparent about the limits. I have never seen any reference to stream limits in Apple docs so even if it isn't exactly a technical bug, I'd argue that it's a documentation bug.
