### ISSUE TITLE
Incosistent bahavior with exhaustive pattern match completion

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals#3023]
**Describe the bug**

When using an exhaustive pattern match completion there is an inconsistency with names and prefixes. See example below with `Success`.

```scala
object Main extends App {
  sealed trait MyTry
  object MyTry {
    case class Error(msg: String) extends MyTry
    case class Option() extends MyTry
    case class Success() extends MyTry
  }

  val x: MyTry = ???
  x match {
    case MyTry.Error(msg) => ???
    case MyTry.Option() => ???
    case Success() => ???
  }
}
```
However, if I had `import scala.util.Success` in scope then the case would be `case MyTry.Success() => `

**Expected behavior**
Names and their prefixes should be consistent no matter what.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.5

**Comment by tgodzik** [comment]
Thanks for reporting! Not sure if it's exactly an error, since I can imagine that some people might want the type to be always the shortest possible and that is the current behaviour.

It would probably be a lot of work to actually make it work like suggested, since the types are printed independently.

Connected to https://github.com/scalameta/metals/issues/2700

**Comment by tgodzik** [comment]
Let's close it and open up a feature request if this bejaviour should be changed
