### ISSUE TITLE
Unable to run simple hello-world scala example

### ISSUE THREAD

**Issue by Alexander770** [scalameta/metals#3075]
**Describe the bug**

  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  Debugging is not supported because bloop server is running on a JRE C:\Program Files\Java\jre1.8.0_281 with no support for Java Debug Interface: 'JDI implementation is not provided by the vendor'. To enable debugging, install a JDK and restart the bloop server -->

**To Reproduce**

**Installation:**

- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.10.5

  Message: Internal error.
  Code: -32603 

**Search terms**

[metals.log](https://github.com/scalameta/metals/files/7072527/metals.log)

**Comment by ckipp01** [comment]
Thanks for the report @Alexander770. The message you posted actually points towards your issue. Bloop needs to be running on a JDK in order to support debugging, and it's running on a JRE. You'll have to install a full JDK and ensure that Bloop is started with that.

## Steps to fix this

- Stop Bloop either with `bloop exit`, or just kill the process
- Install a JDK
- Let metals start bloop again
- If that doesn't work, make sure your `JAVA_HOME` is pointing to the newly installed JDK.
- If you still can't get it to work, you can hard code it here https://scalacenter.github.io/bloop/docs/server-reference#custom-java-home

**Comment by Alexander770** [comment]
Thanks

No matter what I did reinstall java, reinstall VScode, recreated the project (hello-world), switched to Java 8, defined and redefined env variables the error persists. 

Please see the attached log: 
[metals.log](https://github.com/scalameta/metals/files/7074871/metals.log)

**Comment by Alexander770** [comment]
![scala_vscode_error](https://user-images.githubusercontent.com/53492569/131300889-f1e5af39-7dc2-49a7-8b8f-efa60c72bf00.jpg)
![vscode_settings](https://user-images.githubusercontent.com/53492569/131300895-3dbd6c3a-5a55-487b-ba86-e887fff1d924.jpg)
()

**Comment by ckipp01** [comment]
> Thanks
> 
> No matter what I did reinstall java, reinstall VScode, recreated the project (hello-world), switched to Java 8, defined and redefined env variables the error persists.
> 
> Please see the attached log:
> [metals.log](https://github.com/scalameta/metals/files/7074871/metals.log)

Looking at the logs it still seems that Bloop is being started with a JRE instead of the JDK. Are you sure you stopped it before setting the new `javaHome`? Are you able to check the output of `bloop about`? It should tell you what JDK it's running with there.

**Comment by Alexander770** [comment]
How to stop it and how I check the output of bloop?

**Comment by ckipp01** [comment]
If you have Bloop CLI installed you can do a `bloop exit` to stop Bloop. Then Metals should automatically start it up again and you can use the command `bloop about` to see what I mentioned above.

**Comment by ckipp01** [comment]
No it didn't. Maybe something easier to try is just `Metals: Restart Build Server` command from VS Code.

**Comment by Alexander770** [comment]
Can I stop Bloop by Using VScode tools?

**Comment by ckipp01** [comment]
> Can I stop Bloop by Using VScode tools?

Yes, exactly as I just mentioned. The `Metals: Restart Build Server` is shutting down Bloop and then starting it again. So then it should pick up the new JDK.... hopefully

**Comment by Alexander770** [comment]
It has an option: Disconnecting from Bloop session...

**Comment by Alexander770** [comment]
i disconnected and reconnected again it still says: 
 bloop server is running on a JRE C:\Program Files\Java\jre1.8.0_281 

how can I control it?

**Comment by ckipp01** [comment]
Have you tried https://scalacenter.github.io/bloop/docs/server-reference#custom-java-home?

**Comment by Alexander770** [comment]
Tried, still: **2021.08.30 11:51:30 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b**

**Comment by LingarajVB** [comment]
Hello,
I am also facing the same issue, I have java installed on mac and even i was trying hello-world project but its not working.

<img width="941" alt="Screenshot 2022-01-14 at 8 00 33 PM" src="https://user-images.githubusercontent.com/39855043/149
<img width="481" alt="Screenshot 2022-01-14 at 7 57 26 PM" src="https://user-images.githubusercontent.com/39855043/149532208-6bf99c73-96af-44a3-88da-088798750e38.png">
532181-d605b1b7-6eb2-4f18-ad87-b3f47ef6f2a8.png">



PS: i did not install bloop on mac since metals has the utility with it since its forcing me to update mac which i am hesitant to do it.
