### ISSUE TITLE
"expected start of definition" error

### ISSUE THREAD

**Issue by sicr0** [scalameta/metals#3189]
**Describe the bug**
I run `sbt new scala/scala3.g8` to generate a Scala 3 
project. After when I edit it with **Vim** (I have only **coc-metals** installed) I always get the message _expected start of definition [scalameta:]_. Metals doesn't suggest anything else when I type.

**To Reproduce**

1. Run `sbt new scala/scala3.g8`
2. Edit it with **Vim** using **coc-metals**
4. See error on **@main def Main**

**Expected behavior**
No error showing and the suggester should aid me providing methods names.

![Screenshot_20211007_162850](https://user-images.githubusercontent.com/49662650/136450068-727b4ffa-a0c8-4434-b913-820519a33564.png)

**Installation:**

- Operating system: Linux
- Editor: Vim
- Metals version: v0.10.7

**Comment by ckipp01** [comment]
Thanks for the report @sicr0, this is due to the previous fallback version being 2.12 for metals meaning that when you first open a project, it assumes it's in 2.12 until everything gets registered and it thinks you're in 3.x land. In the latest snapshots of Metals this is changed and should fix this for you. Feel free to give it a try following the instructions [here](https://scalameta.org/metals/docs/editors/vim#using-latest-metals-snapshot) or wait until the next release.
