### ISSUE TITLE
Align the documentation of how to do debugging with official docs, help beginners to get started with debugging

### ISSUE THREAD

**Issue by bjornregnell** [scalameta/metals#3272]
I'm trying to help my beginner programming students to grok how to use the debugger in vs code and one problem is that this page https://code.visualstudio.com/docs/editor/debugging does not mention Scala and this page https://scalameta.org/metals/docs/editors/vscode/#running-and-debugging-your-code does not really show how to do debugging in vs code and it is not really aligned with the official doc on the debugger and how to set it up. 

**Expected behavior**

Align the info and make it easier for a beginner programmer to get started with debugging with Metals. Would it even be possible for the official MS doc on vs code to point also to the Scala extension and for the Metals VS code page to align or link to the setup as in the official guide to reduce confusion?

**Comment by bjornregnell** [comment]
Example of misalignemnt: On the official docs it says to press the "Launch program" button but in Scala Metals it is "Run and Debug" but the it starts a run config and that is more diffcult than just press "debug" above your @main. But that does not happen if you dont have a build.sbt etc.

**Comment by bjornregnell** [comment]
If you follow the offical docs you risk ending up with 
![image](https://user-images.githubusercontent.com/3601817/140535803-b2cbd5cf-e9cf-47dc-bd12-1335cd32c312.png)

**Comment by bjornregnell** [comment]
I guess Metals need to fix a launch config in order for the official docs to work. If we cannot impact the offical docs then we need to adapt so they work. Searching for "vs code debug" will land most beginners on the official docs...

**Comment by tgodzik** [comment]
Related https://github.com/scalameta/metals-vscode/pull/767 <- however I don't think it will cause Metals to pop up on the main page, but should be more discoverable.

**Comment by bjornregnell** [comment]
How about providing a launch config out-of-the-box so the standard "Launch Program" button "just works"?

**Comment by tgodzik** [comment]
> How about providing a launch config out-of-the-box so the standard "Launch Program" button "just works"? Is this related to the label? Or what does it take to provide such a config to avoid the 'JSON with Comments' popup...

I am thinking we could try and run the existing command that will try to discover a main method in the current file instead of creating the config with the pop ups, which I never really found too useful. 

We could also link to the official docs from the Metals page as it's much more complete when it comes to the debugging explanations, what do you think?

**Comment by bjornregnell** [comment]
Well, as long as the button that is given if you just click the Bug-tab on the left and the launch button just works then its fine (I thought that youperhaps had to have a launch config in order for the button to work)

**Comment by tgodzik** [comment]
> Well, as long as the button that is given if you just click the Bug-tab on the left and the launch button just works then its fine (I thought that there perhaps had to exist a JSON launch config in order for the button to work, but if it's not needed then its fine)

I think it should be possible to not need it, but I ahven't managed yet to figure it out https://github.com/microsoft/vscode/issues/54212

**Comment by tgodzik** [comment]
Ok, so I did some research and I think currently the best approach would be to prefill the launch.json configuration for the user instead of making the users fill everything by themselves. This will require some discover endpoint on the Metals side, but it can be done on top of https://github.com/scalameta/metals/pull/3277

We can also use the dynamic configuration, which shows up when users run `Select and start debugging` command, which will not create the launch.json config, but users will still be able to choose it in the `Run and debug` tab.

I am also thinking of adding another dynamic configuration option for running things in the current file, which could be resolved dynamically based on the current open file. It would be cool to have that instead available as the default F5 behaviour, but I think that's not possible and the best thing we can do is prefill the json (will need to confirm that still.)

**Comment by bjornregnell** [comment]
That sounds promising! :heart_decoration:

**Comment by tgodzik** [comment]
This should now work properly when just clicking run in any file. Do let us know @bjornregnell if there is anything else you feel we can improve (aside from obvious Metals stability)

**Comment by bjornregnell** [comment]
Works like a charm! :heart:
