### ISSUE TITLE
Expand Selection selects too wide scope

### ISSUE THREAD

**Issue by doofin** [scalameta/metals#3615]
### Describe the bug

When use selection->Expand Selection,it sometimes selects the wrong range

Reproduction:
1.type single line some comment 
2.put  cursor before `//` or after `//`
3.expand selection will select wrong block

In addition,it's also problematic with expand selection on block comment `/* */`

### Expected behavior

expand selection should only select the comment block when cursor is before before `//` or after `//`

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.1

### Extra context or search terms

Expand ,Selection
probably relates to https://github.com/scala/vscode-scala-syntax/issues/49

**Comment by tgodzik** [comment]
Thanks for reporting! This is related to the fact that the Scala parser omits comments, we should probably do a similar thing to what we do for keywords in https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/Keywords.scala#L66

Check if we are in the comment and expand the selection for it otherwise do it normally.

**Comment by doofin** [comment]
@tgodzik Could you give me some advice on how to achieve this in more details ? and do we need to change Scala parsers in scalameta library?

**Comment by tgodzik** [comment]
A very similar issue was in https://github.com/scalameta/metals/pull/2822/files  where we wanted to not show completions inside comments. We could use the same mechanism to check if we are in a comment and if we are we would probably need to use the Scalameta tokenizer to find the enclosing scope.

It would need to be implemented in:

For Scala 2:
https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-2/scala/meta/internal/pc/SelectionRangeProvider.scala 

For Scala 3:
https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala

Of course we don't need to do both at the same time, but the solution would be similar.

**Comment by doofin** [comment]
thanks! I will have a look

**Comment by tgodzik** [comment]
For Scala 3 we have https://github.com/scalameta/metals/blob/main/mtags/src/main/scala-3/scala/meta/internal/pc/completions/KeywordsCompletions.scala#L75 <- comments are handled there. We would probably need to also check if we are in a comment and if so the next range should be the range of that comment.

> where the trees returned by openedTreeswill prune all the coments. Does that mean we have to modify in InteractiveDriver inpackage dotty.tools` 

That's why we use the scalameta tokenizer for the task, which also handles tokens.

**Comment by tgodzik** [comment]
We merged the support for Scala 2, Scala 3 support should look very similar.

**Comment by doofin** [comment]
thanks @tgodzik , what is the Scala 2 correspondence of https://github.com/scalameta/metals/blob/2014643e75359c018d93b24bf12f948b68d2a71c/mtags/src/main/scala-3/scala/meta/internal/pc/SelectionRangeProvider.scala#L49 ?

**Comment by tgodzik** [comment]
That should be `lastVisitedParentTrees`
