### ISSUE TITLE
Calls to `doctor.check` on each build target compilation significantly degrade performance

### ISSUE THREAD

**Issue by pvid** [scalameta/metals#3755]
### Describe the bug

Using recent SNAPSHOT versions, I encountered a significant delay between saving a file and editor receiving diagnostics. It went from nearly imperceptible to > 10 seconds.

It is happening in a module that transitively depends on multiple other modules in a large sbt project. I managed to track the issue down to`doctor.check()` being called on each build target compilation.

https://github.com/scalameta/metals/blob/c2d8baa140b675bf900b1783daad2fa9eceeb424/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L427)

It is triggered even on no-op compilation, so the number of calls scale with the size of module dependencies.

Using a locally published metals version with that call removed fixes my issue, but I did not examine what it means for the new compilation status feature of the doctor. The `Doctor#check` method seems to go through all build targets on every call. I would image that it should just update the status of build targets whose compilation status changed. 

### Expected behavior

Do not run a heavy operations on no-op compilations

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.2+49-ee7372d7-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! @kpodsiad it's probably related to your changes?

**Comment by kpodsiad** [comment]
@pvid could you try https://github.com/kpodsiad/metals/tree/fix/doctor-check out? Personally, I don't have access to any codebase big enough to see what the difference looks like.

**Comment by pvid** [comment]
@kpodsiad thank you for the quick turnaround! That version seems to fix the issue 👍

**Comment by kpodsiad** [comment]
Glad to hear that it helps, but unfortunately it's rather quick & dirty than a rightful fix.

The problem is that Metals server doesn't know anything about vscode's Doctor panel, if it is open or closed. Without knowing that fact server doesn't know if reloading doctor is necessary or not. 

One possible solution is to keep track of its state on the server side. However, AFAIK clients like nvim just display doctor in json and don't have such dedicated view which can stay opened.

Although there is `metals-doctor-reload` command already, it takes an already computed html or json. In case when doctor window is closed then the result is discarded - `Reload the HTML contents of an open Doctor window, if any. Should be ignored if there is no open doctor window.`
I think introducing a new command `metals-refresh-doctor` is justified and makes sense. It will just notify the client that there might be an doctor client, but it'll up to the client what to do with this information.

Is `metals-doctor-reload` vscode specific command and what do you think about `metals-refresh-doctor`?

cc: @ckipp01 @tgodzik

**Comment by ckipp01** [comment]
> The problem is that Metals server doesn't know anything about vscode's Doctor panel, if it is open or closed. 

🤔 I wonder if it's possible at all to have something similar to `treeViewVisibilityDidChange`. Would it be possible that when the doctor panel gets opened we fire something like a `doctorVisibilityDidChange` notification to Metals and we track that, and we don't compute any doctor stuff unless it's open or unless we need to compute it to send along with a `metals-doctor-[run|reload]`?  

> However, AFAIK clients like nvim just display doctor in json and don't have such dedicated view which can stay opened.

Yea at least for nvim it's not something that really remains open, but something you just reference from time to time.

**Comment by kpodsiad** [comment]
> I wonder if it's possible at all to have something similar to treeViewVisibilityDidChange. Would it be possible that when the doctor panel gets opened we fire something like a doctorVisibilityDidChange notification to Metals

Yes, it is possible to do that in vscode. But if other clients don't keep doctor opened won't it be too vscode specific? (or it's rather more universal approach, I cannot decide between these options).

Anyway, I'll go with visibility change events and see how it works.

**Comment by ckipp01** [comment]
> Yes, it is possible to do that in vscode. But if other clients don't keep doctor opened won't it be too vscode specific? (or it's rather more universal approach, I cannot decide between these options).

I think this should be ok in other editors as well. I know in Neovim it won't be an issue to send this when we open it and again when it gets closed.

**Comment by tgodzik** [comment]
What if we cached the doctor info so that we wouldn't recalculate everything? Is it the main problem here that check invokes a lot of calculations for the problem resolver?

Alternatively, maybe we could include the compilation status in the treeview and keep that cached on the client side? We could nicely color the failing projects in the metals view.

**Comment by kpodsiad** [comment]
> What if we cached the doctor info so that we wouldn't recalculate everything? Is it the main problem here that check invokes a lot of calculations for the problem resolver?

That sounds like a good plan for future improvement 👍🏻 . However, I'll go with the visibility change for now as its less demanding.

**Comment by kpodsiad** [comment]
@pvid there is a new pre-release version of vscode's extension. Could you try it and get us confirmation that the problem is gone?
