### ISSUE TITLE
"Resolution error: Error downloading org.scalameta:metals_2.12:0.11.2+103-92415c3d-SNAPSHOT"

### ISSUE THREAD

**Issue by tribbloid** [scalameta/metals#3764]
### Describe the bug

1. Open any sbt project with VSCode insider
2. get the error message

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

2.12:0.11.2+103-92415c3d-SNAPSHOT

**Comment by tribbloid** [comment]
```
Resolution error: Error downloading org.scalameta:metals_2.12:0.11.2+103-92415c3d-SNAPSHOT
  not found: /home/peng/.ivy2/local/org.scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/metals_2.12-0.11.2+103-92415c3d-SNAPSHOT.pom
  download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/scalacenter/releases/org/scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/metals_2.12-0.11.2+103-92415c3d-SNAPSHOT.pom) while downloading https://dl.bintray.com/scalacenter/releases/org/scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/metals_2.12-0.11.2+103-92415c3d-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/public/org/scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/metals_2.12-0.11.2+103-92415c3d-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/metals_2.12/0.11.2+103-92415c3d-SNAPSHOT/metals_2.12-0.11.2+103-92415c3d-SNAPSHOT.pom
Downloading Metals failed with the following:
Process exited with code 1
```

**Comment by kpodsiad** [comment]
We've recently migrated the codebase from 2.12 to 2.13 and that's why there is no snapshot for `_2.12` suffix. What's your extension version?

It seems like you modified `server version` manually, didn't you?

There are two options hot to solve this issue:
- you can remove `server version` and use default one which is compatible with your current vscode's Metals extension version
- you can switch to the pre-release version (here [doc's how to do it](https://scalameta.org/metals/docs/editors/vscode#installation)) of the extension which is compatible with the newest snapshots. (although being on the pre-release is a little bit cutting edge)

**Comment by kpodsiad** [comment]
@tribbloid I'll close this issue, but if you still have mentioned errors feel free to reopen it.

**Comment by tribbloid** [comment]
Yes you are right, the metal server version has been set to a SNAPSHOT version by the previous version. After removing it everything becomes normal.

The default/reset value is however 11.2, still not optimal and will become obsolete soon

**Comment by ckipp01** [comment]
> The default/reset value is however 11.2, still not optimal and will become obsolete soon

That's the latest stable version. The default will also fall back to this. So when we release the next version of Metals, the extension will also be updated to fall back to the latest version.
