### ISSUE TITLE
 no build target for test file

### ISSUE THREAD

**Issue by camgraff** [scalameta/metals#3936]
### Describe the bug

After importing the build and indexing [lila](https://github.com/lichess-org/lila). I navigate to https://github.com/ornicar/lila/blob/master/modules/user/src/test/TotpTest.scala and there is no LSP functionality. From `.metals/metals.log` I see 
```
2022.05.20 21:11:42 WARN  no build target for: /home/cam/projects/lila/modules/user/src/test/TotpTest.scala
```
however, the build target does exist i.e. running `sbt "project user" test` runs the test.

I see the same behavior with all of the test files in that project. 

### Expected behavior

LSP functionality should work on these test files.

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.5

**Comment by ckipp01** [comment]
Thanks for the report @camgraff! So looking a bit closer, the issue is actually here:

https://github.com/lichess-org/lila/blob/master/project/BuildSettings.scala#L22-L23

This line:

```
Test / bloopGenerate := None,
```
means that there is nothing generated for test targets meaning that Bloop / Metals won't know about this targets. You can verify this by looking at the Doctor and seeing that there is no `user-test` target. If you would comment this line out and re-import you'll then see that everything works as expected in the file you mention.

Looking at the contributing section about [Bloop](https://github.com/lichess-org/lila/wiki/Lichess-Development-With-Bloop) it doesn't mention anything about this, so my only guess is that _maybe_ this is done to safe some time, but it will probably trip people up like it has here. You'd have to ask over there why this is done.

**Comment by camgraff** [comment]
Ah ok, thanks!
