### ISSUE TITLE
.sc file gets error in VScode 

### ISSUE THREAD

**Issue by ZongHan13** [scalameta/metals#4035]
### Describe the bug
When I open a project in vscode which is  builded by mill then metals will detect Ammonite script, it will ask you to import `.sc` file or not.
![截圖 2022-06-15 20 23 10](https://user-images.githubusercontent.com/63963971/173829615-3d08af00-a564-4dcf-984e-79a0cca93bf1.png)
---

If choose import or Automatically all the `.sc` file will get error like this.
![截圖 2022-06-15 20 45 03](https://user-images.githubusercontent.com/63963971/173830017-98fe36bb-2167-4207-af17-f4c8083fc805.png)
![截圖 2022-06-15 20 45 47](https://user-images.githubusercontent.com/63963971/173830238-48ef246f-da0b-4f5a-ab48-ed3dc3aedbef.png)
---
When import ammonite script metals output 
![截圖 2022-06-15 21 50 21](https://user-images.githubusercontent.com/63963971/173844547-3324e5db-8df9-4d94-aa7f-e20d49416f09.png)
---

Metals Run doctor 
![截圖 2022-06-15 21 57 08](https://user-images.githubusercontent.com/63963971/173845672-cf516ecd-5485-4428-886e-3ad315c7969b.png)
### And the error part 
![截圖 2022-06-15 21 58 07](https://user-images.githubusercontent.com/63963971/173845700-636bf962-8182-4590-8a31-f25a09917002.png)

But if choose dismiss metals  will working  fine.
![截圖 2022-06-15 20 48 58](https://user-images.githubusercontent.com/63963971/173830776-311693b7-20cb-4635-9d08-8ca4b6911e3e.png)
----
Reproduce step:
1. Create mill project.
2. Open project will VScode
3. When metals detect ammonite script import script
---

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.06

### Extra context or search terms

Ammonite, VScode, metals

**Comment by tanishiking** [comment]
Hmm, Metals should show `New Mill workspace detected, would you like to import the build?` popup instead of detecting `build.sc` as an Ammonite script.
I tried to reproduce the issue, but I couldn't get `Ammonite script detected` for `build.sc` 🤔 
Does anybody have any ideas who know more about mill/ammonite support?

**Comment by ckipp01** [comment]
> Does anybody have any ideas who know more about mill/ammonite support?

Yea I'm able to mimic this. It only happens when you have an ammonite script at the root of your build as well as your `build.sc`. So let's say you have:

```
build.sc
test.sc
```
and you open up `test.sc` you'll first be prompted to import your mill build, but then you'll also get a prompt to import your ammonite scripts. When you do that, then you hit on issues since it seems to report errors for you build file when it should be ignoring them.

**Comment by dos65** [comment]
@ckipp01 Nice catch! After your explanation I've noticed that `test.sc` is presented on the screenshot :smile:

**Comment by ckipp01** [comment]
I think the issue might be here:

https://github.com/scalameta/metals/blob/859dac6c220d015efe6f74b8a08a21780a809c40/metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala#L265-L266

Since when we do trigger Ammonite, we load up the current script and all the opened ones and filter by `.isAmmoniteScript`, but that will take any `*.sc`.

**Comment by ZongHan13** [comment]
> and you open up `test.sc` you'll first be prompted to import your mill build, but then you'll also get a prompt to import your ammonite scripts.

Sorry about that, you are right.
