### ISSUE TITLE
Implement textDocument/hover

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#431]
<img width="742" alt="screenshot 2018-12-20 at 16 39 29" src="https://user-images.githubusercontent.com/1408093/50294283-d7d11780-0475-11e9-9ebf-9bb9bf1283e9.png">

**Comment by tanishiking** [comment]
I'm working on this LSP endpoint, and it is roughly working :)
https://github.com/tanishiking/metals/commit/28488bed36616409a47ddf4e454f6ebbfc4737e5

<details>
<summary>Demo on VSCode (on scalafix)</summary>

![peek 2019-01-02 14-56](https://user-images.githubusercontent.com/9353584/50584733-bb40d080-0eb4-11e9-8457-4c9b1672b1dc.gif)

</details>



However, I found that there are some TODOs for realizing the practical endpoint for `textDocument/hover`.

- [ ] Move [PrettyType](https://github.com/scalacenter/scalafix/blob/182806a13840e54c8ea624e5934f7423e7d4d904/scalafix-core/src/main/scala/scalafix/internal/util/PrettyType.scala)  (and [QualifyStrategy](https://github.com/scalacenter/scalafix/blob/4b47cb2f50f11be50bca32897c6ddaca9a6ea35b/scalafix-core/src/main/scala/scalafix/internal/util/QualifyStrategy.scala)  and [TypeExtractors](https://github.com/scalacenter/scalafix/blob/d6728deaf0c66a56336eeb19c92697d8593fb97a/scalafix-core/src/main/scala/scalafix/internal/util/TypeExtractors.scala) which are currently used from [ExplicitResultTypes](https://github.com/scalacenter/scalafix/blob/4b47cb2f50f11be50bca32897c6ddaca9a6ea35b/scalafix-rules/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala)) into `scalameta/scalameta`.
  - [My implementation](https://github.com/tanishiking/metals/commit/28488bed36616409a47ddf4e454f6ebbfc4737e5) uses `PrettyType` which is almost copied from `scalafix`, because `PrettyType` is quite useful for constructing practical hover information which contains type information of the symbol on the position. If `scalameta` has a `PrettyType` and make this endpoint use it instead, we can delete the `PrettyType` from this implementation.
  - I consider that moving them into `scalameta/scalameta` (or it's contrib?) is reasonable because they are related only on `scalameta` (not dependent on `scalafix`)
- [ ] (For better hover information)(maybe) fix https://github.com/scalameta/scalameta/issues/1494
  - As we can see from the demo gif above, we cannot retrieve enough information from some of symbols, because they don't have signature and falling back to [here](https://github.com/tanishiking/metals/blob/28488bed36616409a47ddf4e454f6ebbfc4737e5/metals/src/main/scala/scala/meta/internal/metals/PrettyType.scala#L165-L211) in `PrettyType#toTree`.
  - For retrieving better hover information, we should ensure the most of symbols have a signature.
  - Since I'm not familiar with signature computing, maybe I'm misunderstanding and there are some other workaround...

**Comment by tanishiking** [comment]
Thank you for reviewing on my approach!
It seems better and straightforward to retrieve the hover information from a presentation compiler since it will give us more accurate information about a symbol than `PrettyType` :+1:

This commit was just a prototype implementation, but I should have asked on gitter or this issue, thank you for your advice :)

**Comment by olafurpg** [comment]
Now that #527 is merged, we have the infrastructure to implement this. Current master has a rudimentary implementation of `hover` with a few basic tests but in order to enable the feature we need a clean reimplementation and to write a lot of tests covering cases like patterns, types, extension methods, annotations, named arguments, packages, `apply`, for comprehensions and full chain of identifiers in fully qualified names like `scala.collection.mutable.ArrayBuffer`.

Also, we need a new type printer that pretty-prints modifiers and symbol kinds

```scala
// Ok
implicit val global: ExecutionContext
// Not Ok
ExecutionContext
```

**Comment by olafurpg** [comment]
Opened a PR implementing hover #595

**Comment by zachlefevre** [comment]
How can I use this feature in vim?

**Comment by ayoub-benali** [comment]
It is a command you trigger, there aren't key bindings by default but here you can find the recommended ones: https://scalameta.org/metals/docs/editors/vim.html#recommended-cocnvim-mappings
