### ISSUE TITLE
SemanticDB "generation" broken for Scala 2.13.9

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals#4449]
### Describe the bug

Metals 0.11.8
Bloop (SBT plugin) 1.5.3

Scala 2.13.8
![image](https://user-images.githubusercontent.com/677147/192740559-ea291173-1f3f-4523-9b1c-84338f40995f.png)

Scala 2.13.9
![image](https://user-images.githubusercontent.com/677147/192740618-2c7a8cd8-66d6-4533-a653-1272bdf39c8d.png)

I tried once with Bloop sbt plugin v1.5.3-42-75a0d6ee too, but no difference.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.8

**Comment by tgodzik** [comment]
Thanks for reporting! This should actually work ok, does it happen still after restarting the build server?

**Comment by tgodzik** [comment]
Do you seen anything in `metals.log` pointing to problems downloading the new semanticdb plugin?

**Comment by spangaer** [comment]
https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.9/4.5.11/semanticdb-scalac_2.13.9-4.5.11.jar

Downloads just fine with curl

**Comment by tanishiking** [comment]
Hmm, I also confirmed semanticdb generation failed for 2.13.9 with Metals server 0.11.8 🤔 
`0.11.8+181-d8bafc76-SNAPSHOT` works fine FYI @spangaer

**Comment by armanbilge** [comment]
Not entirely sure if it's related, but I've been having problems with sbt-metals. AFAICT my issue is because this setting is evaluating to `false`.
https://github.com/scalameta/metals/blob/d8bafc765a58e7b005c4a843444e7bd5fac101b8/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala#L91-L95

Almost definitely because `supportedScala2Versions` does not include `2.13.9` for sbt-metals `0.11.8`.

**Comment by tanishiking** [comment]
Looks like Metals can't enable semanticdb plugin until the next release. For the time being please use the latest snapshot versions :bow:

Maybe we should remove the check @armanbilge mentioned so that we can use all Metals features without waiting for the next release.
I guess this check is added when the semanticdb is not yet widely supported in scala versions, but now recent Scala versions support semanticdb generations/plugins. I assume we can safely remove that check.

**Comment by tanishiking** [comment]
Thank you for reporting @spangaer and thanks for your pointer @armanbilge !

**Comment by tgodzik** [comment]
> Maybe we should remove the check @armanbilge mentioned so that we can use all Metals features without waiting for the next release.

We should actually, since we now backpublish it should be safe do to so. Could you raise a PR for that @tanishiking ?

> Hmm, I also confirmed semanticdb generation failed for 2.13.9 with Metals server 0.11.8 thinking
0.11.8+181-d8bafc76-SNAPSHOT works fine for me FYI @spangaer

This seems to be another problem actually, I will look into that.

**Comment by tgodzik** [comment]
We need to change that in Bloop it seems :/

**Comment by tgodzik** [comment]
@spangaer if you update Bloop version in Metals to `1.5.3-44-03658369` it should work.
