### ISSUE TITLE
Incorrect case completions

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals#4515]
### Describe the bug

Happens on both 2.13 and 3
```scala
//> using scala "2.13.8"

object CaseCompletions {
  val x: Option[Int] = ???
  x match {
    case None        => ca@@
    case Some(value) =>
  }
}
```
<img width="429" alt="Screenshot 2022-10-12 at 18 33 39" src="https://user-images.githubusercontent.com/37124721/195399224-895511eb-17ae-4336-b4e3-315b362d609a.png">

### Expected behavior

Don't offer incorrect completions.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by jkciesluk** [comment]
Thanks for reporting!
 The problem here is that we were not distinguishing between
 ```scala
 case A => ca@@
 // and 
 case A =>
 ca@@
 ```
 I see two simple solutions:
 1. Suggest next `case` completion only after there is something after the `=>` in the previous one.
 2. Check if the next `ca@@` is in different line than the previous one. This might be better, because someone might want to list all cases before handling them
