### ISSUE TITLE
`*.worksheet.sc` ignores Scala version and setups inconsistent Scala version.

### ISSUE THREAD

**Issue by i10416** [scalameta/metals#4537]
### Describe the bug

Environment

- mac os (M1)
- java 11
- metals v0.11.9
- Build server currently being used is scala-cli v0.1.15.

Reproduction steps

```
mkdir tmp
cd tmp
scala-cli setup-ide .
code .
```

a.worksheet.sc

```scala

//> using scala "2.13.10"

scala.util.Properties.versionString
// res0: String = "version 2.13.9"
```

a.worksheet.sc with `using scala "2.13.10"` pops up warning

> Scala 2.13.10 is not supported in worksheets. Falling back to 2.12.17 without your classpath. Consider using 2.13.9 instead to fix this.

Then, I downgrade Scala version to 2.13.8 and reload window.
It does not show warning, but it uses incorrect Scala version(2.13.9). Note that `metals doctor` returns correct Scala version(2.13.8).

```scala
//> using scala "2.13.8"

scala.util.Properties.versionString
// res0: String = "version 2.13.9"
```

Then, I upgrade scala version to 3.2.0 and reload window. 
It does not show warning, but it uses incorrect Scala version(2.13.8). Note that `metals doctor` returns correct Scala version(3.2.0).

```scala

//> using scala "3.2.0"

scala.util.Properties.versionString
// res0: String = version 2.13.8
```

After deleting all dot files in workspace and reload window returns the same result.

```scala
//> using scala "3.2.0"
scala.util.Properties.versionString
// res0: String = version 2.13.8
```

In addition, importing library via `$ivy`, it downloads Scala 3 artifacts, but versionString returns `2.13.8`(metals doctor shows 3.2.0)
```scala
import $ivy.`org.typelevel::cats-core:2.8.0`

scala.util.Properties.versionString
// res0: String = version 2.13.8
```

In all the cases above, metals output says `Using presentation compiler with project's scala-library version: 3.2.0`

### Expected behavior

Developers can configure Scala version with `using` directive and Metals respects the configuration.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tanishiking** [comment]
@i10416 Thank you for reporting!
Unfortunately, worksheets don't support using directives. It is a ScalaCLI feature, and worksheets are not driven by ScalaCLI (it works with https://github.com/scalameta/mdoc).
Worksheets just ignore `//> using scala "2.13.8"` as a normal inline comment and use a presentation compiler version that the project using (if the worksheet doesn't belong to any project, fallback to the default compiler version).

It should improve somehow because it sounds a bit confusing because both worksheet and ScalaCLI scripts a `.sc` extension, and I understand people think using directives should work for worksheets.

There would be 2 options

- Support using directives in worksheets (mdoc)
  - Not sure how hard is, but it sounds pretty nice
- Show warning for using directives in worksheets like it doesn't work for worksheets
  - the thing is if we run `scala-cli foo.worksheet.sc`, using directive works...

**Comment by tanishiking** [comment]
BTW, the warning is incorrect (it actually should work), 
> Scala 2.13.10 is not supported in worksheets. Falling back to 2.12.17 without your classpath. Consider using 2.13.9 instead to fix this.

the warning will be suppressed by https://github.com/scalameta/metals/pull/4535

**Comment by tgodzik** [comment]
I think we can create a feature request to allow to change scala version for worksheets, otherwise this works as expected.

**Comment by i10416** [comment]
> Support using directives in worksheets (mdoc)

Ah, I didn't know worksheet feature is implemented with mdoc under the hood! Thank you.

> Not sure how hard is, but it sounds pretty nice

I feel the same. 
When I recommend Scala to Python or JS devs, worksheet is one of the appealing features.

**Comment by tgodzik** [comment]
Opened up a feature request: https://github.com/scalameta/metals-feature-requests/issues/308

For now you should be able to use any Scala version if you chose a specific Scala version in Metals settings or it should use any version that is used in a project if the worksheet is created along other source files.
