### ISSUE TITLE
Issue with Java imports not being resolved

### ISSUE THREAD

**Issue by oscar-broman** [scalameta/metals#4625]
### Describe the bug

Minimal repro, JVM 19:

1. Clone repo: https://github.com/oscar-broman/metals-issue
2. Open in VSCode with Metals
3. Import the project
4. Navigate to LoggerProxy.java
5. Wait until the project is fully imported and a Java project is added

### Expected behavior

There shouldn't be any errors shown in `LoggerProxy.java`, but I see loads of errors.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/1629077/200955837-25fa872c-4553-4fbd-9a00-6b4691e384c8.png">

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9 and 0.11.9+105-80f10362-SNAPSHOT

**Comment by tgodzik** [comment]
Thanks for reporting! That actually comes from the Java plugin, which doesn't work too well with Metals. You might try generating eclipse config from sbt and that could help, but it might be a bit rocky.

The only issue I had was that I didn't have JDK 19 installed:
```
2022.11.10 13:06:43 WARN  Unexpected javac output: error: invalid source release: 19
Usage: javac <options> <source files>
use --help for a list of possible options.
```

You might need to specify it in javaHome and it should also update Bloop java home automatically.

Otherwise, without those options navigation seems to work.
