### ISSUE TITLE
Metals won't run application due to length of classpath/command line on Windows

### ISSUE THREAD

**Issue by UtilFunction** [scalameta/metals#4827]
### Describe the bug

Trying to run an application in VSCode on Windows by pressing the run button will not work with a larger amount of dependencies due to the length of the classpath. A `command line is too long` error message will appear instead.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.10

**Comment by kpodsiad** [comment]
Solution: https://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows   
Location in code that need to be changed: https://github.com/scalameta/metals/blob/cfd7cc6650df46bb70fb8b442c13aeb0265dbb75/metals/src/main/scala/scala/meta/internal/metals/debug/ExtendedScalaMainClass.scala#L49

**Comment by Abhijeetmishr** [comment]
@kpodsiad Should I pick up this ?

**Comment by kpodsiad** [comment]
Hey @Abhijeetmishr! If only you are interested then yes, feel free to do this. In case of any questions you can ask here or in scalameta discord (link is somewhere at https://scalameta.org/). Can I assign this issue to you then?

**Comment by Abhijeetmishr** [comment]
@kpodsiad Yes I am interested and thanks for quick reply.
I have forked and cloned repo also I am starting with this.
In case of query I will ping.

**Comment by kpodsiad** [comment]
@Abhijeetmishr I described how one can work with Metals [here](https://github.com/scalameta/metals/pull/4795#pullrequestreview-1239764410). Test can be found [here](https://github.com/scalameta/metals/blob/cfd7cc6650df46bb70fb8b442c13aeb0265dbb75/tests/unit/src/test/scala/tests/CodeLensLspSuite.scala#L404-L432)

**Comment by Abhijeetmishr** [comment]
@kpodsiad Here are some of the findings listed.


There are two ways we could go about solving this:

> 1. Make it a config option as to whether classpath ordering is maintained, when it's set to false, then use JDK wildcard expansion for the classpath.
> 2. Implement a loader that will load the classpath specification from a text file, and create a new classloader from that.



 **Original issue raised here: [https://github.com/playframework/playframework/issues/2025]**

**Comment by kpodsiad** [comment]
@Abhijeetmishr I think that manifest JAR should be enough, isn't it? I looked how bloop solves that issue and I found https://github.com/scalacenter/bloop/pull/1118. Maybe you can do something similar?

**Comment by Abhijeetmishr** [comment]
@kpodsiad cool

**Comment by tgodzik** [comment]
@Abhijeetmishr did you have any luck with this? We might need to fix it for the next release, which I plan at the end of this month and I don't want to hurry you, so if you don't have time to work on it I can work on it.

**Comment by Abhijeetmishr** [comment]
@tgodzik Yeah I have gone through this [](https://github.com/scalacenter/bloop/pull/1118) if you guide me a bit through this JAR manifestation thing I can wrap it up as earliest as possible.
I have experience working with and wanted to explore more but this JAR thing is new to me, pardon me if I am asking more.

**Comment by tgodzik** [comment]
I think there should be plenty of information to look into for example https://www.baeldung.com/java-jar-manifest 

We would basically need to copy https://github.com/scalacenter/bloop/pull/1118/files#diff-fb531c2a4247390172fdf02b6a2f9ea078e0b24ce01ea24de28251e2cf504f3fR151 just without the Task, since we only use Scala Future.

I would also name the jar by calculating MD5 of the classpath so that we only create the manifest jar once per classpath change. We can create them in temporary directory and make them delete once Metals exits.

**Comment by Abhijeetmishr** [comment]
@tgodzik @kpodsiad sorry for delaying this thing but after trying researching a lot on this followed all the reference provided by you people i think i willnot be able to do this  because this JAR manifestation/packaging thing is new to me.
Please assign this to someone and i would love to follow along as a junior developer.
Regards

**Comment by tgodzik** [comment]
Sure! I will take a look, this is a tough topic :wink:
