### ISSUE TITLE
Implement All Members doesn't play nice with scala 3

### ISSUE THREAD

**Issue by robmwalsh** [scalameta/metals#4869]
### Describe the bug

This will either not work at all or insert the members above the class.

start with:
```scala
sealed trait Demo {
  def implementMe: Int
}

case class ADemo(value: Int) extends Demo
```
expected error~
```
[error] 7 |case class ADemo(value: Int) extends Demo
[error]   |           ^
[error]   |class ADemo needs to be abstract, since def implementMe: Int in trait Demo in package demo is not defined 
```

run implement all members

nothing happens, or methods are inserted above `ADemo` (and in the case of case classes, includes `productArity` and other stuff the compiler generates)

### Expected behavior

method stubs should be inserted in the class they're missing from. 

Compiler-generated methods should not be inserted

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

0.11.10

### Extra context or search terms

Scala 3.2.1

Build server currently being used is Bloop v1.5.6. (Reset)

Metals Java: 17.0.4.1 from Eclipse Adoptium located at /home/rob/.sdkman/candidates/java/17.0.4.1-tem

Metals Server version: 0.11.10

**Comment by tgodzik** [comment]
Thanks for reporting! We'll take a look!

**Comment by keynmol** [comment]
![2023-01-31 16 30 03](https://user-images.githubusercontent.com/1052965/215844733-0973f096-f803-465f-9110-13dfcdcc78bc.gif)

It still seems to work weird - only if I have a companion object..

**Comment by jkciesluk** [comment]
The issue with inserting too many methods or inserting them in the wrong place is solved, now the issue is that the `path` to `ADemo` tree starts with definition of `apply` method and is followed by `TypeDef ADemo$`, which we don't want. If we have companion object, `apply` method is moved there, so the path is correct and contains `TypeDef ADemo` (without `$`). 

I will take a look at that. Also, it's surprising  that in test the path was fine
