### ISSUE TITLE
Does not work with integration tests

### ISSUE THREAD

**Issue by keirlawson** [scalameta/metals#503]
**Describe the bug**
When using Metals 0.4.0 with Atom and editing integration tests (set up with SBT's `Defaults.itSettings` in `src/it`) the editor says "no build target" and no metals functionality is available for these files.

**To Reproduce**
1. Navigate to a scala file within `src/it`
2. Modify the file to insert an error
3. Node that no red squiggly is provded

**Expected behavior**
red squiggly highlights error

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Atom
- Metals version: v0.4.0

**Comment by gabro** [comment]
Hi @keirlawson thanks for reporting.

This is likely due to Bloop exporting only projects for the `Compile` and `Test` sbt configurations. You can follow the steps here https://scalacenter.github.io/bloop/docs/build-tools/sbt#enable-custom-configurations to enable Bloop on the `IntegrationTest` configuration too.

**Comment by keirlawson** [comment]
Ah yes, following those steps does resolve the issue.

I guess it would be nice to have a solution that didn't involve adding bloop to the build though, as with compile and test this is not required.

**Comment by olafurpg** [comment]
I agree it would be nice if there was a way to automatically enable the integration test configuration without explicitly installing sbt-bloop. There's not much we can do on the Metals side to fix this, OTOH. cc/ @jvican
