### ISSUE TITLE
No suggestions / completion for opaque type in another package

### ISSUE THREAD

**Issue by aflierl** [scalameta/metals#5366]
### Describe the bug

1 . In the following short example, type `+ Mee` and hit `ctrl + space` to get completion suggestions.
2. Actual behaviour: There are no suggestions.

```scala
package demo.app

@main def main: Unit = println("Hello World: ")

package somewhere {
  opaque type Meep = Long

  object Meep:
    def apply(m: Long): Meep = m
    extension (m: Meep) def value: Long = m

  final case class Moop(value: Long)
}
```

### Expected behavior

I would expect to get a completion for the companion object of the opaque type `Meep`, the same way I get suggestions for the case class `Moop` if I had typed `+ Moo` instead.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.12

### Extra context or search terms

Scala version: 3.3.0
I've tried this with both Bloop and SBT as the BSP server and the behaviour is the same. As an example with complete project setup, I've provided: https://github.com/aflierl/opaque-type-completion

**Comment by kasiaMarek** [comment]
So the bug comes from the fact that a companion object for a top-level type gets in semanticdb the same additional prefix as the type `FileName$package.`. So in `ScalaTopLevelMtags` we were emitting incorrect tokens (once, that couldn't be mapped correctly to semanticdb tokens). I have fixed the issue for the case when type definition appears **before** the companion object definition.

Unfortunately doing this for the other case requires amending already emitted symbols. Since you'd usually put the companion object after the type I'm wondering if it's worth it.

CC: @tgodzik @tanishiking
