### ISSUE TITLE
Incorrect errors shown for project with relative ProjectRefs

### ISSUE THREAD

**Issue by andreasWallner** [scalameta/metals#6003]
### Describe the bug

When working with an sbt project that depends on local folders via a ProjectRef, compilation fails in VSCode using Metals even though it builds fine using sbt.
This seems to be a regression compared to earlier version, judging from comments in the very much related #507.

Reproduction uses an updated version of the one from #507: sbt version is updated to 1.9.8 and the workaround mentioned in #507 (setting `bloopAggregateSourceDependencies` is already added)

Steps to reproduce:
- clone repository: `git clone https://github.com/andreasWallner/metals_import_test.git`
- run VSCode in `p1` folder: `code metals_import_test/p1`
- import build

Looking at the log output we get this warning:
```
...
2024.01.07 23:09:56 INFO  Connected to Build server: Bloop v1.5.13
2024.01.07 23:09:59 INFO  time: indexed workspace in 2.74s
2024.01.07 23:10:13 INFO  skipping build import with status 'Installed'
2024.01.07 23:10:13 WARN  Missing project 'p2' may cause compilation issues in project 'root'
2024.01.07 23:10:13 INFO  compiling root (1 scala source)
2024.01.07 23:10:13 INFO  time: compiled root in 0.24s
```

"Problems"  will be shown for all references to P2.

In the wild in encountered this issue while working on this project: https://github.com/SpinalHDL/VexiiRiscv, but the reproducer shows the same issue.

### Expected behavior

I'd expect that no "Problems" are shown in VSCode and that intellisense / code navigation works for packages depended on via ProjectRef.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.2.0

### Extra context or search terms

Java: OpenJDK 17.0.9
Visual Studio Code: v1.67.0

**Comment by tgodzik** [comment]
Thanks for reporting! We will take a look at that project whenever we can to see what exactly is the issue. In the meantime switching build server to sbt BSP might be a workaround.

**Comment by andreasWallner** [comment]
@tgodzik Thanks for the hint. Using the sbt BSP all the subprojects are found. I'm having some issues with the build, but that's another topic.

**Comment by kasiaMarek** [comment]
In your reproduction you have an old `1.2.8` version of sbt in `p2`, which seems to be causing problems. After changing it to `1.9.8`  the workspace works as expected. 

Note that for `bloopAggregateSourceDependencies` to work the sub-project needs to be first correctly exported to bloop. Metals does that for you, so best if you do the following:
1. first open `p2` in vscode and import the build
2. then add `p1` as a [workspace folder](https://code.visualstudio.com/docs/editor/multi-root-workspaces) to your workspace

That way you'll have both modules side by side:
https://github.com/scalameta/metals/assets/26606662/ea104665-6d3c-4423-96b9-67a25ff68041

Otherwise if you're not interested in opening and developing the sub-project. You can manually add [bloop plugin](https://scalacenter.github.io/bloop/docs/build-tools/sbt) and run `sbt bloopInstall` to export the sub-project to bloop.

Finally, `bloopAggregateSourceDependencies` seems to be by default set to `true` now, so it's no longer needed.

I hope this helps.
