### ISSUE TITLE
Non-expanded @define variables in Scaladoc

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#648]
See the report in https://github.com/scalameta/metals/issues/598#issuecomment-482091256

The example source file is here: https://github.com/scala/scala/blob/v2.12.1/src/library/scala/collection/IterableLike.scala#L1

This is where the variable `coll` is used

![image](https://user-images.githubusercontent.com/691940/55958028-06167500-5c68-11e9-8def-d9ff2c2755fe.png)

This is where the variable is defined

![image](https://user-images.githubusercontent.com/691940/55958050-10387380-5c68-11e9-8836-6035d82b46eb.png)

/cc @mudsam who worked on this

_Originally posted by @gabro in https://github.com/scalameta/metals/issues/598#issuecomment-482098367_

**Comment by olafurpg** [comment]
This is an intended/known limitation in how we expand `@define` macros. I couldn't find clear docs on how it works in Scaladoc, but my observation is that variables can be defined in supertypes and referenced from subtypes, and vice-versa. In Metals we only expand variables that are defined in the same source file. 

I suspect this limitation is not a big problem for most codebases besides the standard library (I'm happy to be convinced otherwise). I propose we move to metals-feature-requests since it's not a feature I personally expect to work on in the near future.

**Comment by olafurpg** [comment]
A feature that I believe would be worth implementing which might solve this issue along the way is to fallback to the docstring of overriden symbols if the referenced symbol has no documentation.
```scala
trait Animal {
  /** Make sound */
  def sound(): Unit
}
class Dog extends Animal {
  def sound(): Unit = println("woof")
}

new Dog().sound() // hover on "sound" shows `Animal.sound` docstring
```

**Comment by gabro** [comment]
Makes sense 👍 tracking this as a feature request in https://github.com/scalameta/metals-feature-requests/issues/16
