### ISSUE TITLE
OOM while running tests

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#6521]
### Describe the bug

Originally raised in https://github.com/scalameta/metals/issues/6484, but it's not related. It's most likely an issue in Bloop

Citing original posts:

I am facing also this issue when I run tests within vscode. I've created a public github repo where the issue can be reproduced:

- clone https://github.com/kostaskougios/metals-bugs.git
- open the project with vs code
- monitor memory usage of bloop.Server with jconsole
- open MapGeneratorTest and run it many times. Eventually the bloop.Server process will run out of memory

In my box it starts bloop.Server with 3GB of ram. It takes several runs to run out of memory, about 8 runs but  lets say in 10-20 runs it should definatelly run out of mem with 3GB. But you can see that it piles up memory if you run jconsole and click the "memory" tab. Memory usage increases and even if you run a "GC" it doesn't go down (by much), eventually more and more memory is used until it runs outofmem.

<img width="864" alt="image" src="https://github.com/scalameta/metals/assets/1302046/db047cd8-8963-4abb-8469-21728e95577a">
 

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

### Extra context or search terms

OOM test explorer

**Comment by kostaskougios** [comment]
Hi @tgodzik , it seems that this bug is no more. I tried the above project of mine, running the test and monitoring boop.Server memory, and it garbage collects now, always dropping below 100MB after running a GC which is good.

<img width="878" alt="image" src="https://github.com/scalameta/metals/assets/1302046/9319717a-bdae-4b93-9cbe-8a7b485bec03">

I've run the test many times and it all seems good now. Do you know of any change that may have fixed it? I am on

<img width="524" alt="image" src="https://github.com/scalameta/metals/assets/1302046/d914da6e-d2af-4596-9263-3b771d5f87b6">
but installed also a snapshot that fixed an other bug I was interested. Bloop seems to be on    
bloop-frontend_2.12-1.5.18.jar

**Comment by kostaskougios** [comment]
(this issue seems to be fixed now)

**Comment by tgodzik** [comment]
I am not aware of anything that could have fixed it :thinking: But again I am not aware of anything that could have caused it in the first place :sweat_smile: 

Let's keep it open for a while to see if that repeats. Might be a concurrency issue that causes some resources not to be freed.
