### ISSUE TITLE
Metals hangs out "Starting Metals server..." a long time

### ISSUE THREAD

**Issue by happyieee** [scalameta/metals#6762]
**Describe the bug**

I built Scala with metals on vscode. I used it well the other day. Yesterday, I don't know if it suddenly stopped working because I uninstalled some useless software. The plug-in appears to have stopped at some stage without any error message other than "Starting" Metals servers "hangs here. My computer is correctly configured with JDK17. JAVA_HOME is also correctly added to the environment variable. I tried reloading the vscode and metals plugins, but it didn't work.

![image](https://github.com/user-attachments/assets/5617ef34-1593-4892-8901-57faa1b6b5a1)

**To Reproduce**

1.Open a Scala project
2. Metals hongs out "Starting Metals server..." a long time

**Screenshots**

Metals output:
![image](https://github.com/user-attachments/assets/cda4235b-1f0d-4ca9-b442-e256dd49670d)

Extension Host output:
![image](https://github.com/user-attachments/assets/e7906991-1224-4c56-b950-e11a95d0ea4f)

**Installation:**

- Operating system: `Windows 11`
- JAVA version : `JDK 17`
- VSCode version: `v1.92.2`
- Metals version: `v1.39.0`

**Comment by kirillsemyonkin** [comment]
+1 for the same issue on roughly the same pc specs. tried deleting every .bloop and .metals i could find, and updating whenever there are updates, and nothing helps for roughly the same time period as this issue is open. unable to work on my scala project, luckily i have other non-scala projects to do, but imagine this happening to someone who doesnt have this kind of luxury. would be great if i could temp fix it by downgrading, but downgrading the extension doesnt help and i dont know where to downgrade everything else...
