### ISSUE TITLE
no completions showing or types

### ISSUE THREAD

**Issue by mikedmcfarland** [scalameta/metals#690]
When triggering suggest, I see no completions available from metals. 
I still see errors at points, problems, and can use goto definition. However peeking types and completions do not seem to work.
**To Reproduce** Steps to reproduce the behavior:

1. type some code
2. press `^ Space` to trigger suggestion
3. see no suggestions

**Screenshots**

<img width="678" alt="Screen Shot 2019-04-21 at 7 33 14 PM" src="https://user-images.githubusercontent.com/3240061/56478486-fddee680-646c-11e9-978f-700be3d6570c.png">

**Installation:**

- Operating system: macOS
- VSCode version: Version 1.33.1 (1.33.1)
- VSCode extension version: Name: 1.3.1
- Metals version:  0.5.0
- Java version: openjdk version "1.8.0_212"

**Comment by gabro** [comment]
It seems like the presentation compiler doesn't cope well with that flag.

On the other hand, I've done some digging, and it appears the `-Xcheck-null` is gone in 2.12 and it was already obsolete in 2.11.

See this extract from the compiler code (`2.11.x` branch):

https://github.com/scala/scala/blob/d209ff49442a902bd0492a72c9862841d36d32cc/src/compiler/scala/tools/nsc/settings/Warnings.scala#L112

Here's the commit where the `-Xcheck-null` option was removed because it did nothing: https://github.com/scala/scala/commit/a4c338888f4364dfd44989acd12cb72daf639081#diff-6a32b09e0e5ebfd45d5af148012f231b

In general, Metals should not interfere with your compiler options (so keep the reports flowing in case you find other incompatibilities), but - in this case - I would advise you to drop that specific option, for the reasons above.

Hope this help!

**Comment by mikedmcfarland** [comment]
Thanks for the info, makes sense.
