### ISSUE TITLE
Deprecated annotations squiggle the whole body of a class/trait

### ISSUE THREAD

**Issue by mwz** [scalameta/metals#719]
**Describe the bug**

Annotating traits/classes with deprecated annotations causes the whole body of the trait/class to be squiggled, which can be quite distracting as it obstructs code readability. Would it be possible to reduce the scope of the warning just to the trait/class name instead of the whole body?

**To Reproduce**
Compile the following code and see the whole body of the Trait and Class being squiggled and reported as warnings.

```scala
@deprecated("this is going away", "2.12.0")
class asdf extends scala.annotation.Annotation

@asdf
trait Trait {
  def hello: Unit 
}

@asdf
final class Class {
  def hello: Unit = {
    ???
  }
}
```

**Expected behavior**

Expected to see the warning squiggles appear only under the trait and class names, not the whole body.

**Screenshots**

![Screenshot 2019-05-12 at 22 29 03](https://user-images.githubusercontent.com/1190768/57587977-5e5dc280-7505-11e9-8992-c8df537ae1c6.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.2

**Comment by olafurpg** [comment]
Thank you for reporting! I'm not sure how much we can change about this behavior on the Metals side, we forward diagnostics from the compiler which reports those positions for the deprecation messages. 

One (not so great) workaround is to remove the `-deprecation` flag 🤔

**Comment by mwz** [comment]
Hi @olafurpg, I've checked that when I compile the above snippets via sbt I can see the warnings pointing to characters 7 and 13, which is the beginning of `Trait` and `Class` however VSCode seems to report those warnings starting from the beginning of the line 🤔. Could this be a bug in how those positions get either collected or propagated through metals (because the compiler seems to report the correct positions)?

**Comment by mwz** [comment]
I've checked that bloop also reports the correct position (at least in the standard output), like sbt. It seems like this diagnostic gets converted/overridden incorrectly somewhere down the line (assuming it's not bloop that sends the incorrect data via bsp, which I'm still yet to verify).
I'm still trying to get my head wrapped around the codebase, but I'll keep digging - maybe I can figure out what's happening. If you can think of any particular things I should check any suggestions would be much appreciated.

**Comment by olafurpg** [comment]
@mwz

**Comment by olafurpg** [comment]
@mwz the position of error messages reported by the compiler is usually defined by three different offset positions
- `start`: the start offset of the range position
- `end`: the end offset of the range position
- `point`: an offset between start and end where the caret should point to when printing the error to stdout (such as from `sbt compile` or `bloop compile`).

Example:
```scala
@annotation final class Hello extends Product { val message = "Hello" }
^start                  ^point                                        ^end
```

Metals uses only the `start` and `end` offsets to display errors in the editor. The problem with this particular issue is that the Scala reporter uses the position of the class when reporting a deprecation warning on the annotation. The error message should use the position of the annotation instead. This is a Scala compiler bug and I suspect it's easy to fix in the compiler. Feel free to report to https://github.com/scala/bug/ (I can still reproduce in 2.13.0-RC2).

We could implement workarounds in Metals to use `point` instead but I would argue that would still result in confusing error messages for the end user since it points to the class name instead of the annotation reference.

```scala
depr.scala:10: warning: class asdf is deprecated (since 2.12.0): this is going away
final class Class {
            ^
```

One workaround is to disable deprecation warnings for Metals by removing the `-deprecation` option from build.sbt when the environment variable `METALS_ENABLED` is set to `true`.
