### ISSUE TITLE
Literal types not accepted as identifiers

### ISSUE THREAD

**Issue by heksesang** [scalameta/metals#787]
**Describe the bug**
When using string literals as types, as is supported by Scala 2.13, Metals provides an error from scalameta that `identifier expected but string constant found`. With integer literals the same happens, with the message `identifier expected but integer constant found`.

The code compiles fine.

**To Reproduce**
1. Add the line `val o: Option["name"] = ???` to any valid location in a 2.13 project.

**Expected behavior**
No errors in the IDE.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.6.1+90-cde40f08-SNAPSHOT

**Comment by olafurpg** [comment]
Thank you for reporting! We are still using the 2.12 dialect for parsing `*.scala` files, I suspect the fix is to update this line here 
https://github.com/scalameta/metals/blob/cde40f088cddcc9b504f493ca3a0d839c394110e/metals/src/main/scala/scala/meta/internal/metals/Trees.scala#L53

to use `Scala213`.
