### ISSUE TITLE
Disable dot as a commit character when writing imports

### ISSUE THREAD

**Issue by jad-hamza** [scalameta/metals#791]
**Is your feature request related to a problem? Please describe.**

I have an sbt project where some Scala files are unmanaged by sbt. In these files, I can write imports that are unknown to sbt, and in that case metals might replace them with imports in the standard library. For instance, when I write `import Environment.`, the moment when I enter the dot, the whole line is replaced with: `import java.rmi.activation.ActivationGroupDesc.CommandEnvironment.`

**Describe the solution you'd like**

I would like to have an option to disable dot as a commit character.

**Comment by jad-hamza** [comment]
That was quick, thanks!

**Comment by olafurpg** [comment]
Having coded quite intensively with Metals recently on the latest stable version (not since this issue was fixed), I've hit on other situations where the commit character is also problematic:

- when writing a renamed prefix like `l.Range` then I may type "l." and then insert then follow up with `import org.eclipse.{ls4p => l}`. With commit characters, the "l." completes to an unrelated item.
- when the project does not compile, the compiler symbol table quickly goes off-sync and doesn't pick up new symbols that are defined since the last compile error. In this case it's really annoying when you have  meticulously typed the full name of a new symbol and then "."  select a different identifier.
