### ISSUE TITLE
Treeview commands inconsistent

### ISSUE THREAD

**Issue by dsyzling** [scalameta/metals#838]
I've noticed commands returned by the new treeview in the Build tree appear a little inconsistent and wondered if this was by design. Commands for Import build, connect to build server etc. can be sent directly to the Metals lsp server to initiate the action. However when classes/functions are shown under the Project hierarchy the command sent by Metals is "metals.goto". I have to strip the "metals." prefix when sending the workspace/executeCommand otherwise Metals sends a message via window/logMessage of unknown command metals.goto.

**Installation:**

OS is Windows and Arch Linux.
Editor is Emacs.
Metals version is 0.7.0+45-2d3960b4-SNAPSHOT and -Dmetals.execute-client-command=on
I'm currently not using the metals.editor=emacs version to avoid any conflicts with the compiled config since I'm not sure whether client-command is enabled in this snapshot. So for the avoidance of doubt I'm downloading a custom build with client commands enabled for testing.

**Comment by tgodzik** [comment]
Not sure about it, need to think about that one. @olafurpg will know more.

**Comment by olafurpg** [comment]
Thank you for reporting! The IDs are indeed inconsistent. The reason some IDs include the `metals.` prefix is to avoid conflicts with VS Code commands. In some cases the VS Code extension automatically adds the `metals.` prefix while in other cases like for `metals.goto` it doesn't.

To remedy the situation I propose we try to use the following convention

- by convention, always use `metals.` prefix for all Metals commands so that client integrations can safely register those command IDs without conflicting with other editor plugins.
- when executing commands, strip optional `metals.` prefix so that clients that send commands such as `"build-import"` continue to work.

WDYT?

**Comment by olafurpg** [comment]
A quick fix would be to add a `.stripPrefix("metals.")` to the following line 

https://github.com/scalameta/metals/blob/365293b6ccc64c41f24bb7838660bf8b955cf81d/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L1020

PR welcome!

**Comment by dsyzling** [comment]
From an alternative treeview client provider point of view I'm fine with that. So just to clarify eventually any treeview client (Emacs, VS Code, etc.) would be able to simply send the command sent by Metals as part of the tree elements and not worry about any pre-processing (for example my Emacs client is the one doing the stripPrefix("metals.") at this time. With the fix above, I would then be able to remove my prefix code and the server would be able to cope with both "metals.goto" and "goto" - although I would simply be using the command sent by Metals itself treating it as an opaque command to execute.

**Comment by kurnevsky** [comment]
For me it looks like commands `build-connect`, `build-import`, etc should be wrapped inside `metals-echo-command` so we don't need to handle them as separate commands at all.
