### ISSUE TITLE
Show progress during startup

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#92]
Essentially this:

![](http://g.recordit.co/ZywwHebmlC.gif)

This can leverage the LSP notifications of type "status". The LS will send a notification indicating the status (Starting, Started, Error) and a message.

Each specific editor can decide how to show this message. The example in the GIF above is a mocked implementation in VSCode.

The Java LSP does it exactly like this:
- VSCode-side: https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L80-L99
- LS-side: https://github.com/eclipse/eclipse.jdt.ls/blob/3c872459836f8fb921decb59241f2a30cd84768d/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#L277

**Comment by laughedelic** [comment]
I'm not sure what is `connection.sendStatus` in that code and the "status" type of notifications you mention. `window/logMessage` has only 4 types of message (`MessageType`):
* Error
* Warning
* Info
* Log

We can use `Log` type, of course and then have a convention with clients to treat it specially, but I think this doesn't fit nicely with LSP.

**Comment by gabro** [comment]
Ah, I thought this was a standard lsp features but it looks like it's a custom addition by eclipse lsp? https://github.com/eclipse/eclipse.jdt.ls/blob/0bba050b76ea867564bd6221e78782bc69d09cfa/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JavaClientConnection.java#L39

I'll look it up better tomorrow.

**Comment by laughedelic** [comment]
This is how it looks now in Atom:

![2017-12-03 22 48 54](https://user-images.githubusercontent.com/766656/33530188-3acad064-d87c-11e7-8a5c-665087e96369.gif)

No details about indexing, it just starts spinning when initialization request is sent and stops when it gets a response. And it works even without `logMessage`, because atom-languageclient allows you to hook on pre/post-initialization. I think vscode-languageclient should have something similar. Other requests usually don't take so long, so it's not essential. 

I think that doing the same in VS Code client + implementing #85 will be enough: if you're wondering what exactly is happening, you can check logs. In VS Code there's a special panel for that, in Atom, unfortunately, it's still not implemented..

**Comment by gabro** [comment]
Ah right, without anything fancy, we could probably just use the `onReady` method on the client to show a spinner (without any details).

**Comment by cquiroz** [comment]
@laughedelic I don't see the spinner in Atom, is that change on the plugin?

**Comment by olafurpg** [comment]
I think it's OK to implement vscode specific functionality if it's valuable and not too much work. A progress bar would be super nice for example, it's one of thing I I'd otherwise miss from IntelliJ.

**Comment by gabro** [comment]
The problem is that we need to define some custom message over the protocol to communicate the progress from the server to the client. The Java LSP seems to do just that.

The editor-specific part is how to show the progress, but that's really tiny.

**Comment by ShaneDelmore** [comment]
This looks like it has at least some support from vscode team.  Might be worth using until there is an official answer.  https://github.com/Microsoft/vscode-languageserver-node/pull/261

**Comment by laughedelic** [comment]
@cquiroz Try pulling the master and running `sbt apmPackage` again. I forgot to push an update of  atom-languageclient which adds this feature. If it doesn't work, ping me on Gitter, I'll help you to debug it.

> Ah right, without anything fancy, we could probably just use the onReady method on the client to show a spinner (without any details).

**Comment by olafurpg** [comment]
This should be fairly easy to do now after #176 and #164, we need to first detect if the client supports this feature and then send notifications to the `"status"` endpoint

**Comment by olafurpg** [comment]
After #332, actual indexing of project and dependency sources + semanticdb may be fast enough that it won't be necessary to report progress. The source file indexer processes ~800k loc/s. 

I think it's worth revisiting this however once we have a bsp client that triggers compile in the build tool to report batch compilation progress in the build tool.

**Comment by pca006132** [comment]
Hi, LSP now supports progress report via `$/progress`: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress . Wondering if it is possible to add an option to `statusBarProvider` to use this method, so editor plugins such as https://github.com/j-hui/fidget.nvim can handle this without the need to special case metals.

**Comment by ckipp01** [comment]
Hey @pca006132 we actually have a feature request for this here: https://github.com/scalameta/metals-feature-requests/issues/125. We have a couple different custom LSP extension that we use in instead of progress to enable us to do a few more things, but it is a good idea to default to progress when the client doesn't support `metals/status`.
