### ISSUE TITLE
Add .bloop and .metals automatically to .gitignore if it already exist

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#966]
Whenever new workspace is created we should add .metals and .bloop to be gitignored automatically, since it should never be added to a git repository

**To Reproduce**
1. Clone any Scala repo
2. Start up Metals
3. .metals and .bloop will show up in git

**Expected behavior**
Nothing should be discovered by git

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.7.6

**Search terms**
git gitignore .bloop .metals

**Comment by ceedubs** [comment]
I just tried out the latest Metals snapshot, and I am not a fan of this behavior. I've been using Metals for quite some time now with `.metals/` and `.bloop/` in my global gitignore file. Now Metals is starting to make changes to the `.gitignore` files for work projects despite the changes being specific to the user's development environment as opposed to the project itself. For example, many of my coworkers use IntelliJ, so these changes aren't relevant to them. I think that this would be even more of a problem when making changes to open source projects, where a PR could easily accidentally involve unrelated `.gitignore` changes. I think that user-specific gitignore rules should be managed by user gitignore settings instead of being pushed to all projects that the user works on.

**Comment by gabro** [comment]
I share some of the concerns, now that @ceedubs voiced them.
Could we maybe use a showMessage and let the user decide? This would give the option to also permanently opt out from the behavior.

**Comment by tgodzik** [comment]
> I share some of the concerns, now that @ceedubs voiced them.
> Could we maybe use a showMessage and let the user decide? This would give the option to also permanently opt out from the behavior.

I think that might make sense. Will try to do it with show message.

**Comment by tgodzik** [comment]
I was talking with @olafurpg and apparently vscode will include files in search unless you gitignore them, so it would be preferable to have it there. It doesn't work with global gitignore file.

We could add ShowMessageRequest, but it might be to much communication at the start.

**Comment by gabro** [comment]
It's a bit more complicated than that. VSCode can be configured to use global ignore files. See:

![image](https://user-images.githubusercontent.com/691940/66378372-9af9f100-e9b3-11e9-8e58-47ea61c21155.png)

Also, there is a "Search: Exclude" setting which is independent from gitignore

![image](https://user-images.githubusercontent.com/691940/66378466-c67cdb80-e9b3-11e9-84b7-0f3791f9d694.png)

---

Bottom line, I think user-specific configuration is risky territory: we either do this perfectly or we risk to annoy users for relatively little benefit (adding a couple of lines to the .gitignore is fairly painless and you do it once).
See also how sbt does not add `target/` dirs to the .gitignore automatically, but that does not seem to annoy users.

My suggestion is to remove this feature from Metals (it would take a lot of effort to get the UX right) and to send a PR to https://github.com/github/gitignore/ instead. For example, here's the Ensime-specific one https://github.com/github/gitignore/blob/master/Global/Ensime.gitignore (it's also interesting to see this PR https://github.com/github/gitignore/pull/2289 where they move away from local gitignores for tool-specific stuff)

**Comment by jvican** [comment]
Maybe you could ask users if they prefer to add the stuff in their global .gitignore or workspace .gitignore? I think VS Code takes global .gitignore into account.
  
If that's not possible, then it's fine. I don't think we should overthink this.

**Comment by olafurpg** [comment]
I wasn’t aware that VS Code supports global gitignore. In that case I’m in favor of reverting his change. We might want to consider prompting the user to update the global gitignore but that can be left for a future discussion.

**Comment by jvican** [comment]
So, if I'm a beginner and I just install Metals, and I have no idea about what a .gitignore file is, does this mean I need to manually add these entries to the gitignore files not to get bad results when I search for files in the workspace?
  
I propose we come up with a plan before reverting this change :thinking:

**Comment by gabro** [comment]
I understand the concern, but how's that different from opening IntelliJ and getting a lot of `.idea` directories suddenly lying around?

That's why I'm suggesting to leverage a resource like https://github.com/github/gitignore, where beginners can just download pre-made gitignore files.

**Comment by jvican** [comment]
> I understand the concern, but how's that different from opening IntelliJ and getting a lot of .idea directories suddenly lying around?
  
It isn't different, the UX in IntelliJ for beginners isn't great. I'd like to see this problem solved in Metals though, in a way that provides the best UX for both beginners and advanced users.
  
> That's why I'm suggesting to leverage a resource like https://github.com/github/gitignore, where beginners can just download pre-made gitignore files.
  
This is a great idea, we should definitely add our entries to the Scala gitignore. But I'm still missing the workflow of how the user gets to install that gitignore. We should also consider the scenario where the user doesn't know what a gitignore file is in the first place. How do we get them to learn what they are and install them in a reasonable time?

**Comment by gabro** [comment]
> It isn't different, the UX in IntelliJ for beginners isn't great. I'd like to see this problem solved in Metals though, in a way that provides the best UX for both beginners and advanced users.

I absolutely agree with the sentiment. If you know me, you know I tend to obsess over UX :)
However, I currently don't see a scenario where automatically adding entries to a .gitignore helps a lot of users. At least not with a simple implementation.

Adding to the local gitignore risks to be annoying in (at least) these cases:
- you're using a global gitignore
- your workspace lives in a subdirectory of a bigger project which already has an appropriate .gitignore

Given those - I'd say common - scenarios, adding lines automatically will cause those users to constantly struggle with an unwanted diff.

Now, if we want to make this better I think we should follow these principles:
- let the user opt-in (this is potentially unwanted behavior, so users need to be in control)
- let users dismiss the opt-in question forever ("Don't show this again")
- don't overload the user with a bunch of information at startup (it's already a crowded space, and user attention is limited)

If you agree with the principles above (which I personally stand by, but they're of course up to discussion), I think we're facing a significantly more complex problem than it seemed initially.

That's why I propose to take a step back and reason about this appreciating the complexity and thinking in terms of overall priority for the project.

**Comment by tgodzik** [comment]
The problem is that `.bloop` and `.metals` are not the only things added automatically. We also have `/project/metals.sbt` - so people can add it by mistake to the workspace, if we don't gitignore it.

We can send a delayed MessageRequest that would ask about it maybe? Schedule it like 1 minute after import build.

**Comment by ceedubs** [comment]
Something that seems worth bringing up is the frequency with which this comes up. For someone who is cloning a git repository but doesn't know about `.gitignore` files (which sounds rare to me, but we'll leave that aside; I'm all for improving first-time user experience), they see a bunch of garbage files and maybe they check in files that they shouldn't, and then they learn a lesson about `.gitignore`. This probably only happens once, but I'll admit that it's not a great experience.

Now consider someone who has been using Scala and Git for years. They have `.metals/` and `.bloop/` in their global `.gitignore`. But _every_ time that they do work on a project that doesn't have these files in the project `gitignore` Metals tries to add it for them. I think that this would get annoying pretty fast. If we could add a configuration setting to disable this then I would do that and would be happy. But I'm still not convinced that it's a good default behavior. And others who experience this are going to blame Metals (in the beginner's case I think that they'll blame their own lack of knowledge of Git). I think that generally people have an expectation that development tools won't silently modify their project files.

Has this come up as an issue that people have experienced? I would think that a new user would be following the getting started docs pretty closely, and those mention adding to `.gitignore`.

**Comment by oleastre** [comment]
Simple suggestion: wouldn't it be possible to do a call to git to check if `.bloop` and `.metals` are ignored before adding them to `.gitignore` ? 
That way, if the user's global settings are correctly set, metals wouldn't change the `.gitignore` file, and if the user prefers per project ignores, it's added to the local `.gitignore` file.
This should work in most of the cases, except when a users wants to mix both behaviour.

Note also, that I work in a mixed environment with IntelliJ, metals, and even ensime; and we are pretty happy to add all the `.xyz` folders in the project's `.gitignore`. We prefer an extra line in `.gitignore` than a bad commit done by a newcomer in the team.
